name: Install Clang and LLVM
description: >
  Installs Clang and LLVM from the official LLVM apt repository using the
  llvm.sh installer script (https://apt.llvm.org/llvm.sh), then registers
  every clang*-N and llvm*-N binary as an unversioned update-alternatives
  entry.  Any conflicting pre-installed alternative (e.g. from the
  Ubuntu-bundled llvm-18) is evicted first, so tools like clang, clang++,
  clang-format, clang-tidy, llvm-cov, llvm-profdata, etc. are all reachable
  without a version suffix.

  NOTE: clang-22 packages are not yet available in the apt.llvm.org
  repository.  The KyleMayes install-llvm-action marketplace action also does
  not provide pre-built Linux x64 binaries for clang-22.  Use version 21
  until clang-22 packages become available.

inputs:
  version:
    description: LLVM major version to install
    default: '21'
  install-coverage-runtime:
    description: >
      Set to 'true' to also install libclang-rt-N-dev, which provides
      libclang_rt.profile.a required for --coverage builds.
    default: 'false'
  packages:
    description: >
      Space-separated list of LLVM tool names to install (without the version
      suffix), e.g. "clang-format" or "clang-format clang-tidy".
      When empty (default) the full LLVM suite is installed via
      "llvm.sh VERSION all".  When non-empty, only the apt repo is set up
      and only the listed packages (clang-format-VERSION, etc.) are installed.
      Use this for workflows that only need a single tool such as clang-format
      to avoid downloading the entire ~600 MB LLVM toolchain.
    default: ''

runs:
  using: composite
  steps:
    - name: install LLVM packages via llvm.sh (full suite)
      if: ${{ inputs.packages == '' }}
      shell: bash
      run: |
        wget -qO /tmp/llvm.sh https://apt.llvm.org/llvm.sh
        chmod +x /tmp/llvm.sh
        sudo /tmp/llvm.sh ${{ inputs.version }} all

    - name: set up LLVM apt repo and install specific packages
      if: ${{ inputs.packages != '' }}
      shell: bash
      run: |
        VER=${{ inputs.version }}
        # Add the LLVM apt signing key and source list
        wget -qO /tmp/llvm-snapshot.gpg.key https://apt.llvm.org/llvm-snapshot.gpg.key
        sudo gpg --dearmor -o /usr/share/keyrings/llvm-snapshot.gpg /tmp/llvm-snapshot.gpg.key
        CODENAME=$(lsb_release -cs)
        echo "deb [signed-by=/usr/share/keyrings/llvm-snapshot.gpg] \
          https://apt.llvm.org/${CODENAME}/ llvm-toolchain-${CODENAME}-${VER} main" \
          | sudo tee /etc/apt/sources.list.d/llvm-${VER}.list
        sudo apt-get update -q
        # Install each requested package with the version suffix
        PKGS=""
        for pkg in ${{ inputs.packages }}; do
          PKGS="$PKGS ${pkg}-${VER}"
        done
        sudo apt-get install -y --no-install-recommends $PKGS

    - name: register unversioned LLVM/Clang alternatives
      shell: bash
      run: |
        VER=${{ inputs.version }}
        for versioned in /usr/bin/clang*-${VER} /usr/bin/llvm*-${VER}; do
          [ -e "$versioned" ] || continue
          base=$(basename "$versioned" "-${VER}")
          # Remove any pre-installed alternative (e.g. llvm-18) before registering
          sudo update-alternatives --remove-all "$base" 2>/dev/null || true
          sudo update-alternatives --install /usr/bin/"$base" "$base" "$versioned" 100
        done

    - name: install clang coverage runtime
      if: ${{ inputs.install-coverage-runtime == 'true' }}
      shell: bash
      run: |
        sudo apt-get install -y --no-install-recommends \
          libclang-rt-${{ inputs.version }}-dev
