name: Install Clang and LLVM
description: >
  Installs Clang and LLVM from the official LLVM apt repository using the
  llvm.sh installer script, then registers every clang-*-N and llvm-*-N
  binary as an unversioned update-alternatives entry.  Any conflicting
  pre-installed alternative (e.g. from the Ubuntu-bundled llvm-18) is evicted
  first, so tools like clang, clang++, clang-format, clang-tidy, llvm-cov,
  llvm-profdata, etc. are all reachable without a version suffix.

  NOTE on version availability: clang-22 packages are not yet available on
  apt.llvm.org for the GitHub Actions Ubuntu runners, and the KyleMayes
  install-llvm-action marketplace action (https://github.com/marketplace/actions/install-llvm-and-clang)
  also does not provide Linux x64 binaries for clang-22 (latest is 21.x).
  Use version 21 until clang-22 packages become available.

inputs:
  version:
    description: LLVM major version to install
    default: '21'
  install-coverage-runtime:
    description: >
      Set to 'true' to also install libclang-rt-N-dev, which provides
      libclang_rt.profile.a required for --coverage builds.
    default: 'false'

runs:
  using: composite
  steps:
    - name: install LLVM packages via llvm.sh
      shell: bash
      run: |
        wget -qO /tmp/llvm.sh https://apt.llvm.org/llvm.sh
        chmod +x /tmp/llvm.sh
        sudo /tmp/llvm.sh ${{ inputs.version }} all

    - name: register unversioned LLVM/Clang alternatives
      shell: bash
      run: |
        VER=${{ inputs.version }}
        for versioned in /usr/bin/clang-*-${VER} /usr/bin/llvm-*-${VER}; do
          [ -e "$versioned" ] || continue
          base=$(basename "$versioned" "-${VER}")
          # Remove any pre-installed alternative (e.g. llvm-18) before registering
          sudo update-alternatives --remove-all "$base" 2>/dev/null || true
          sudo update-alternatives --install /usr/bin/"$base" "$base" "$versioned" 100
        done

    - name: install clang coverage runtime
      if: ${{ inputs.install-coverage-runtime == 'true' }}
      shell: bash
      run: |
        sudo apt-get install -y --no-install-recommends \
          libclang-rt-${{ inputs.version }}-dev
