# Aider configuration
---
lint-cmd:
  - "cpp: clang-tidy -p . --quiet  --extra-arg-before=--driver-mode=g++ --extra-arg=-std=c++24"
  - "python: black --line-length 120"
  - "python: mypy --strict --show-error-codes --ignore-missing-imports --disallow-untyped-defs --disallow-incomplete-defs"
  - "python: flake8 --max-line-length=120 --ignore=E203,E266,E501,W503"
  - "python: ruff check"
  - "python: pylint --output-format=text --score=no --fail-under=8.0"
  - "shell: shellcheck -x"
  - "yaml: yamllint -d relaxed"
  - "markdown: markdownlint -c .markdownlint.json"
  - "cmake: cmake-lint"

#pre-commit:
#  - "pre-commit run --all-files"

model: openai/claude-opus-4.6
