# Aider configuration
lint-cmd:
  - "cpp: clang-tidy -p . --quiet"
  - "python: pylint --output-format=text --score=no --fail-under=8.0"
  - "shell: shellcheck -x"
  - "yaml: yamllint -d relaxed"
  - "markdown: markdownlint -c .markdownlint.json"
  - "cmake: cmake-lint"

pre-commit:
  - "git ls-files | xargs pre-commit run --files"

chat-model: deepseek/deepseek-coder

