# Aider configuration
---
lint-cmd:
  - "cpp: clang-tidy -p . --quiet"
  - "python: black --line-length 120"
  - "python: mypy"
  - "python: flake8 --max-line-length=120 --ignore=E203,E266,E501,W503"
  - "python: pylint --output-format=text --score=no --fail-under=8.0"
  - "shell: shellcheck -x"
  - "yaml: yamllint -d relaxed"
  - "markdown: markdownlint -c .markdownlint.json"
  - "cmake: cmake-lint"

#pre-commit:
#  - "pre-commit run --all-files"

model: deepseek/deepseek-coder
