- id: gtopt-lint
  name: GTOPT Lint
  description: Run all GTOPT-specific linting checks
  entry: ./scripts/pre-commit/lint.sh
  language: system
  types: [python, c, shell, yaml, markdown, cmake]
  require_serial: true
  verbose: true

- id: gtopt-format
  name: GTOPT Format
  description: Run all GTOPT-specific formatting
  entry: ./scripts/pre-commit/format.sh
  language: system
  types: [python, c, shell, yaml, markdown, cmake]
  require_serial: true
  verbose: true

- id: gtopt-tests
  name: GTOPT Tests
  description: Run GTOPT unit tests
  entry: ./scripts/pre-commit/run_tests.sh
  language: system
  pass_filenames: false
  require_serial: true
  verbose: true
