/**
 * @file      test_all.cpp
 * @brief     All gtopt tests - includes all test_*.hpp files
 * @date      2026-02-21
 * @copyright BSD-3-Clause
 *
 * Includes every individual test .hpp file into a single compilation
 * unit to reduce build time while keeping each test in its own file.
 */

#include <algorithm>
#include <chrono>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <expected>
#include <filesystem>
#include <format>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <memory>
#include <numeric>
#include <optional>
#include <random>
#include <ranges>
#include <sstream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <thread>
#include <tuple>
#include <type_traits>
#include <utility>
#include <variant>
#include <vector>

#include <arrow/api.h>
#include <arrow/io/api.h>
#include <boost/container/flat_map.hpp>
#include <doctest/doctest.h>
#include <gtopt/app_options.hpp>
#include <gtopt/array_index_traits.hpp>
#include <gtopt/arrow_types.hpp>
#include <gtopt/as_label.hpp>
#include <gtopt/basic_types.hpp>
#include <gtopt/battery.hpp>
#include <gtopt/battery_lp.hpp>
#include <gtopt/block.hpp>
#include <gtopt/block_lp.hpp>
#include <gtopt/bus.hpp>
#include <gtopt/bus_lp.hpp>
#include <gtopt/cli_options.hpp>
#include <gtopt/collection.hpp>
#include <gtopt/converter.hpp>
#include <gtopt/cost_helper.hpp>
#include <gtopt/cpu_monitor.hpp>
#include <gtopt/demand.hpp>
#include <gtopt/demand_profile.hpp>
#include <gtopt/element_index.hpp>
#include <gtopt/error.hpp>
#include <gtopt/field_sched.hpp>
#include <gtopt/filtration.hpp>
#include <gtopt/flat_helper.hpp>
#include <gtopt/fmap.hpp>
#include <gtopt/generator.hpp>
#include <gtopt/gtopt_main.hpp>
#include <gtopt/input_context.hpp>
#include <gtopt/json/json_bus.hpp>
#include <gtopt/json/json_demand.hpp>
#include <gtopt/json/json_planning.hpp>
#include <gtopt/json/json_solver_options.hpp>
#include <gtopt/json/json_system.hpp>
#include <gtopt/junction.hpp>
#include <gtopt/label_maker.hpp>
#include <gtopt/line.hpp>
#include <gtopt/linear_interface.hpp>
#include <gtopt/linear_parser.hpp>
#include <gtopt/linear_problem.hpp>
#include <gtopt/multi_array_2d.hpp>
#include <gtopt/mvector_traits.hpp>
#include <gtopt/options.hpp>
#include <gtopt/options_lp.hpp>
#include <gtopt/output_context.hpp>
#include <gtopt/overload.hpp>
#include <gtopt/phase_lp.hpp>
#include <gtopt/planning.hpp>
#include <gtopt/planning_lp.hpp>
#include <gtopt/reserve_provision.hpp>
#include <gtopt/reserve_zone.hpp>
#include <gtopt/reservoir.hpp>
#include <gtopt/scenario.hpp>
#include <gtopt/scenario_lp.hpp>
#include <gtopt/scene_lp.hpp>
#include <gtopt/schedule.hpp>
#include <gtopt/simulation.hpp>
#include <gtopt/simulation_lp.hpp>
#include <gtopt/single_id.hpp>
#include <gtopt/solver_options.hpp>
#include <gtopt/sparse_col.hpp>
#include <gtopt/sparse_row.hpp>
#include <gtopt/stage.hpp>
#include <gtopt/stage_lp.hpp>
#include <gtopt/state_variable.hpp>
#include <gtopt/strong_index_vector.hpp>
#include <gtopt/system_context.hpp>
#include <gtopt/system_lp.hpp>
#include <gtopt/turbine.hpp>
#include <gtopt/uididx_traits.hpp>
#include <gtopt/utils.hpp>
#include <gtopt/waterway.hpp>
#include <gtopt/work_pool.hpp>
#include <parquet/arrow/reader.h>
#include <parquet/arrow/writer.h>
#include <parquet/exception.h>

#include "test_app_options.hpp"
#include "test_array_index_traits.hpp"
#include "test_as_label.hpp"
#include "test_basic_types.hpp"
#include "test_battery.hpp"
#include "test_benchmark_map.hpp"
#include "test_block_lp.hpp"
#include "test_bus.hpp"
#include "test_cli_options.hpp"
#include "test_collection.hpp"
#include "test_converter.hpp"
#include "test_cost_helper.hpp"
#include "test_cpu_monitor.hpp"
#include "test_demand.hpp"
#include "test_demand_profile.hpp"
#include "test_element_index.hpp"
#include "test_error.hpp"
#include "test_filtration.hpp"
#include "test_flat_helper.hpp"
#include "test_flat_helper_uids.hpp"
#include "test_fmap.hpp"
#include "test_generator.hpp"
#include "test_generator_profile_lp.hpp"
#include "test_gtopt_main.hpp"
#include "test_hydro_lp.hpp"
#include "test_ieee14_planning.hpp"
#include "test_junction.hpp"
#include "test_label_maker.hpp"
#include "test_line.hpp"
#include "test_linear_interface.hpp"
#include "test_linear_interface_ext.hpp"
#include "test_linear_parser.hpp"
#include "test_linear_problem.hpp"
#include "test_multi_array_2d.hpp"
#include "test_mvector_traits.hpp"
#include "test_options.hpp"
#include "test_output_context.hpp"
#include "test_overload.hpp"
#include "test_parquet.hpp"
#include "test_parquet_2.hpp"
#include "test_phase_lp.hpp"
#include "test_planning.hpp"
#include "test_reserve_provision.hpp"
#include "test_reserve_zone.hpp"
#include "test_reservoir.hpp"
#include "test_scenario_lp.hpp"
#include "test_scene_lp.hpp"
#include "test_schedule.hpp"
#include "test_schedule_csv.hpp"
#include "test_simulation_lp.hpp"
#include "test_single_id.hpp"
#include "test_solver_options.hpp"
#include "test_sparse_col.hpp"
#include "test_sparse_row.hpp"
#include "test_stage_lp.hpp"
#include "test_state_variable.hpp"
#include "test_strong_index_vector.hpp"
#include "test_system_lp.hpp"
#include "test_turbine.hpp"
#include "test_uididx_traits.hpp"
#include "test_utils.hpp"
#include "test_waterway.hpp"
#include "test_work_pool.hpp"
