# SPDX-License-Identifier: BSD-3-Clause
"""gtopt_check_lp – diagnose infeasible LP files generated by gtopt.

Public API
----------
The main entry point is :func:`gtopt_check_lp.gtopt_check_lp.main` (registered
as the ``gtopt_check_lp`` console script).  All user-facing symbols are also
available directly from this package:

    from gtopt_check_lp import check_lp, AiOptions, analyze_lp_file

Sub-modules
-----------
:mod:`._colors`       — ANSI colour helpers
:mod:`._config`       — Config I/O and interactive setup wizard
:mod:`._ai`           — AI provider integration (Claude, OpenAI, DeepSeek, GitHub)
:mod:`._lp_analyzer`  — LP file static analyser
:mod:`._neos`         — NEOS XML-RPC client
:mod:`._solvers`      — Local and remote solver wrappers
"""

from ._ai import AiOptions, query_ai
from ._config import (
    default_config_path,
    load_config,
    run_interactive_setup,
    save_config,
)
from ._lp_analyzer import (
    LPStats,
    VariableBounds,
    analyze_lp_file,
    format_static_report,
)
from ._neos import NeosClient
from ._solvers import (
    detect_local_solvers,
    run_all_solvers,
    run_iis,
    run_local_coinor,
    run_local_cplex,
    run_local_glpk,
    run_local_highs_binary,
    run_local_highs_python,
)
from .gtopt_check_lp import check_lp, main  # noqa: F401

__all__ = [
    "AiOptions",
    "LPStats",
    "NeosClient",
    "VariableBounds",
    "analyze_lp_file",
    "check_lp",
    "default_config_path",
    "detect_local_solvers",
    "format_static_report",
    "load_config",
    "main",
    "query_ai",
    "run_all_solvers",
    "run_interactive_setup",
    "run_iis",
    "run_local_coinor",
    "run_local_cplex",
    "run_local_glpk",
    "run_local_highs_binary",
    "run_local_highs_python",
    "save_config",
]
