# SPDX-License-Identifier: BSD-3-Clause
"""CLI argument parser for gtopt_check_lp."""

from __future__ import annotations

import argparse

from gtopt_config import get_version

from ._ai import _AI_DEFAULT_PROVIDER, _AI_PROVIDERS
from ._neos import _NEOS_DEFAULT_URL

__version__ = get_version()


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="gtopt_check_lp",
        description=(
            "Analyze an infeasible LP file generated by gtopt.\n\n"
            "Performs static analysis (bound conflicts, empty constraints,\n"
            "numerical range) and optionally finds the IIS using a local\n"
            "solver (CPLEX, HiGHS, COIN-OR CLP/CBC) or the NEOS\n"
            "online server.\n\n"
            "Configuration file\n"
            "------------------\n"
            "Uses the unified ~/.gtopt.conf (INI format).  AI settings go in\n"
            "[global] (shared with other gtopt tools); tool-specific settings\n"
            "go in [gtopt_check_lp].  Run --init-config to create or update.\n\n"
            "[global] keys:\n"
            "  ai_enabled   Enable AI diagnostics: true/false (default: true)\n"
            "  ai_provider  AI provider: claude, openai, deepseek, github, local\n"
            "  ai_model     Model name override (default: provider-specific)\n"
            "  color        Terminal color: auto, always, never (default: auto)\n\n"
            "[gtopt_check_lp] keys:\n"
            "  email        E-mail for NEOS submissions (default: empty)\n"
            "  solver       Solver strategy: all, auto, cplex, highs, coinor,\n"
            "               neos (default: all)\n"
            "  timeout      Max seconds to wait for any solver (default: 5)\n"
            "  neos_url     NEOS XML-RPC endpoint\n"
            "               (default: https://neos-server.org:3333)\n\n"
            "CLI flags override config-file values for the current run."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  gtopt_check_lp error_0.lp\n"
            "  gtopt_check_lp error_0.lp.gz          # gzip-compressed LP\n"
            "  gtopt_check_lp error_0.lp --analyze-only\n"
            "  gtopt_check_lp error_0.lp --quiet\n"
            "  gtopt_check_lp error_0.lp --solver coinor\n"
            "  gtopt_check_lp error_0.lp --solver highs\n"
            "  gtopt_check_lp error_0.lp --solver neos --email user@example.com\n"
            "  gtopt_check_lp error_0.lp --no-neos --solver coinor\n"
            "  gtopt_check_lp error_0.lp --timeout 120\n"
            "  gtopt_check_lp error_0.lp --output report.txt\n"
            "  gtopt_check_lp --last                  # auto-find latest error*.lp[.gz]\n"
            "  gtopt_check_lp --init-config           # create/update config file\n"
        ),
    )

    parser.add_argument(
        "lp_file",
        metavar="LP_FILE",
        nargs="?",
        default=None,
        help=(
            "Path to the LP file.  Omit when using --last to auto-detect "
            "the newest error*.lp file in the current directory."
        ),
    )
    parser.add_argument(
        "--last",
        action="store_true",
        default=False,
        help=(
            "Automatically find and analyze the most recently modified "
            "error*.lp file in the current directory (or its logs/ / "
            "output/ subdirectory).  Overrides LP_FILE when both are given."
        ),
    )
    parser.add_argument(
        "--analyze-only",
        action="store_true",
        default=False,
        help="Perform only static analysis; do not invoke any solver.",
    )
    parser.add_argument(
        "--quiet",
        "-q",
        action="store_true",
        default=False,
        help=(
            "Quiet (non-failing) mode, used by the gtopt binary.\n"
            "Tries every available analysis step without ever exiting with a\n"
            "non-zero code or blocking for user input:\n"
            "  \u2022 Skips the interactive first-run setup wizard.\n"
            "  \u2022 Warns instead of failing when the LP file is missing.\n"
            "  \u2022 Always runs the solver step, even when solver='auto' and no\n"
            "    local solvers are found.\n"
            "  \u2022 Falls back to NEOS if an e-mail is configured; warns if not.\n"
            "  \u2022 NEOS connection failures produce a warning, not an error.\n"
            "  \u2022 AI failures produce a warning, not an exception.\n"
            "Implies --no-setup."
        ),
    )
    parser.add_argument(
        "--no-neos",
        action="store_true",
        default=False,
        help=(
            "Skip NEOS remote submissions even when an e-mail is configured.\n"
            "Useful in air-gapped or offline environments."
        ),
    )
    parser.add_argument(
        "--solver",
        default=None,
        choices=["all", "auto", "cplex", "highs", "coinor", "neos"],
        help=(
            "Infeasibility solver to use.  'all' (default) runs every available\n"
            "solver and combines their diagnoses into one report.  'auto' tries\n"
            "local solvers in order then NEOS, stopping at the first success.\n"
            "Defaults to the value in the config file ('all')."
        ),
    )
    parser.add_argument(
        "--algo",
        default=None,
        choices=["default", "primal", "dual", "barrier"],
        help=(
            "LP algorithm to request when running COIN-OR (CLP/CBC) or CPLEX.\n"
            "When omitted, 'barrier' is used for COIN-OR and CPLEX.  Passed\n"
            "automatically by the gtopt binary to match its own solver settings."
        ),
    )
    parser.add_argument(
        "--optimal-eps",
        type=float,
        default=None,
        metavar="EPS",
        help=(
            "Optimality (dual) tolerance for COIN-OR and CPLEX.  When omitted,\n"
            "the solver's built-in default is used.  Passed automatically by the\n"
            "gtopt binary to match its own tolerance settings."
        ),
    )
    parser.add_argument(
        "--feasible-eps",
        type=float,
        default=None,
        metavar="EPS",
        help=(
            "Feasibility (primal) tolerance for COIN-OR and CPLEX.  When\n"
            "omitted, the solver's built-in default is used."
        ),
    )
    parser.add_argument(
        "--barrier-eps",
        type=float,
        default=None,
        metavar="EPS",
        help=(
            "Barrier convergence tolerance for COIN-OR and CPLEX.  When\n"
            "omitted, the solver's built-in default is used."
        ),
    )
    parser.add_argument(
        "--email",
        default=None,
        metavar="EMAIL",
        help=(
            "E-mail address for NEOS server submissions (required for NEOS).\n"
            "Defaults to the value in the config file."
        ),
    )
    parser.add_argument(
        "--solver-url",
        default=None,
        metavar="URL",
        help=(
            f"XML-RPC endpoint for a NEOS-compatible server "
            f"(default: {_NEOS_DEFAULT_URL})."
        ),
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=None,
        metavar="SECONDS",
        help=(
            "Maximum time in seconds to wait for a solver result.\n"
            "Overrides the 'timeout' value in the config file (default: 5)."
        ),
    )
    parser.add_argument(
        "--output",
        default=None,
        metavar="FILE",
        help="Write the analysis report to FILE (ANSI codes stripped).",
    )
    parser.add_argument(
        "--no-color",
        action="store_true",
        default=False,
        help="Disable ANSI color codes in terminal output.",
    )
    parser.add_argument(
        "--full",
        action="store_true",
        default=False,
        help="Print all solver output lines instead of the last 30 per solver.",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        default=False,
        help="Enable verbose / debug logging.",
    )
    parser.add_argument(
        "-l",
        "--log-level",
        default=None,
        choices=["DEBUG", "INFO", "WARNING", "ERROR"],
        metavar="LEVEL",
        help="Logging verbosity. Overrides --verbose when both are given.",
    )
    parser.add_argument(
        "--config",
        default=None,
        metavar="FILE",
        help="Path to the configuration file (default: ~/.gtopt_check_lp.conf).",
    )
    parser.add_argument(
        "--init-config",
        action="store_true",
        default=False,
        help=(
            "Run the interactive configuration wizard to create or update "
            "~/.gtopt.conf, then exit."
        ),
    )
    parser.add_argument(
        "--no-setup",
        action="store_true",
        default=False,
        help=(
            "Skip the interactive first-run setup even when no config file "
            "exists.  Useful for automated pipelines."
        ),
    )
    parser.add_argument(
        "--show-config",
        action="store_true",
        default=False,
        help="Print the active configuration (from file + CLI overrides) and exit.",
    )
    parser.add_argument(
        "--benchmark",
        action="store_true",
        default=False,
        help=(
            "Benchmark mode: solve the LP file with every available solver\n"
            "using dual and barrier algorithms with threads 0, 2, 4.\n"
            "Reports a timing table instead of infeasibility analysis."
        ),
    )

    # ── AI diagnostics ────────────────────────────────────────────────────────
    ai_group = parser.add_argument_group(
        "AI diagnostics",
        "Send the analysis report to an AI provider for an expert diagnosis.\n"
        "Supported providers: " + ", ".join(_AI_PROVIDERS) + ".\n"
        "Requires the corresponding API key in the environment.",
    )
    ai_group.add_argument(
        "--ai",
        dest="ai_enabled",
        action="store_true",
        default=None,
        help="Enable AI diagnostics (default: on when an API key is available).",
    )
    ai_group.add_argument(
        "--no-ai",
        dest="ai_enabled",
        action="store_false",
        help="Disable AI diagnostics.",
    )
    ai_group.add_argument(
        "--ai-provider",
        default=None,
        choices=list(_AI_PROVIDERS),
        metavar="PROVIDER",
        help=(
            f"AI provider to use: {', '.join(_AI_PROVIDERS)}  "
            f"(default: {_AI_DEFAULT_PROVIDER})."
        ),
    )
    ai_group.add_argument(
        "--ai-model",
        default=None,
        metavar="MODEL",
        help="Model name override.  Defaults to the provider-specific default.",
    )
    ai_group.add_argument(
        "--ai-prompt",
        default=None,
        metavar="PROMPT",
        help=(
            "Custom prompt template for the AI query.  Must contain a "
            "'{report}' placeholder."
        ),
    )
    ai_group.add_argument(
        "--ai-key",
        default=None,
        metavar="KEY",
        help=(
            "API key override.  When omitted, the key is read from the "
            "environment variable for the selected provider."
        ),
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {__version__}",
    )

    return parser
