# SPDX-License-Identifier: BSD-3-Clause
"""Configuration file I/O and interactive first-run setup for gtopt_check_lp."""

import configparser
import shutil
import subprocess
import sys
from pathlib import Path

from . import _colors as col
from ._ai import _AI_DEFAULT_MODEL, _AI_DEFAULT_PROVIDER, _AI_PROVIDERS

_CONFIG_SECTION = "gtopt_check_lp"
_CONFIG_DEFAULTS: dict[str, str] = {
    "email": "",
    "solver": "all",
    "timeout": "5",
    "neos_url": "https://neos-server.org:3333",
    "color": "auto",
    "ai_enabled": "true",
    "ai_provider": "claude",
    "ai_model": "",
    "ai_prompt": "",
}


def default_config_path() -> Path:
    """Return the default config file path: ``~/.gtopt_check_lp.conf``."""
    return Path.home() / ".gtopt_check_lp.conf"


def read_git_email() -> str:
    """
    Read the user e-mail from the git global configuration.

    Returns an empty string when git is not installed or no email is set.
    """
    git_bin = shutil.which("git")
    if git_bin is None:
        return ""
    try:
        result = subprocess.run(
            [git_bin, "config", "--global", "user.email"],
            capture_output=True,
            text=True,
            timeout=5,
            check=False,
        )
        return result.stdout.strip()
    except (OSError, subprocess.TimeoutExpired):
        return ""


def load_config(config_path: Path) -> dict[str, str]:
    """
    Load the config file at *config_path*.

    Returns a dict with keys from :data:`_CONFIG_DEFAULTS`.  Missing keys are
    filled with the defaults.  Returns defaults when the file is absent.
    """
    cfg = dict(_CONFIG_DEFAULTS)
    if not config_path.exists():
        return cfg

    parser = configparser.ConfigParser()
    try:
        parser.read(config_path, encoding="utf-8")
    except configparser.Error:
        return cfg

    if parser.has_section(_CONFIG_SECTION):
        for key in _CONFIG_DEFAULTS:
            if parser.has_option(_CONFIG_SECTION, key):
                cfg[key] = parser.get(_CONFIG_SECTION, key)
    return cfg


def save_config(config_path: Path, cfg: dict[str, str]) -> None:
    """Write *cfg* to *config_path* in INI format."""
    parser = configparser.ConfigParser()
    parser[_CONFIG_SECTION] = cfg
    try:
        config_path.parent.mkdir(parents=True, exist_ok=True)
        with config_path.open("w", encoding="utf-8") as fh:
            fh.write(
                "# gtopt_check_lp configuration\n"
                "# Generated by gtopt_check_lp --init-config\n"
                "# Edit this file to set your defaults.\n\n"
            )
            parser.write(fh)
    except OSError as exc:
        print(
            f"Warning: could not write config file {config_path}: {exc}",
            file=sys.stderr,
        )


# ---------------------------------------------------------------------------
# Solver availability helpers
# ---------------------------------------------------------------------------

_SOLVER_BINARIES = [
    ("cplex", "CPLEX", None),
    ("highs", "HiGHS", "sudo apt install highs"),
    ("clp", "COIN-OR CLP", "sudo apt install coinor-clp"),
    ("cbc", "COIN-OR CBC", "sudo apt install coinor-cbc"),
    ("glpsol", "GLPK", "sudo apt install glpk-utils"),
]


def get_solver_status() -> list[tuple[str, str, bool, str | None]]:
    """
    Return installation status for every known solver.

    Each entry is ``(binary, label, installed, apt_hint)``.
    """
    status = []
    for binary, label, hint in _SOLVER_BINARIES:
        installed = shutil.which(binary) is not None
        if binary == "highs" and not installed:
            try:
                import highspy  # noqa: F401, PLC0415  # pylint: disable=unused-import

                installed = True
                hint = None
            except ImportError:
                pass
        status.append((binary, label, installed, hint))
    return status


def print_solver_status(use_color: bool = True) -> None:
    """Print a table of available and missing solvers with installation hints."""

    def _c(code: str, text: str) -> str:
        return f"{code}{text}{col._RESET}" if use_color else text  # noqa: SLF001

    print(_c(col._BOLD, "\nSolver availability:"))  # noqa: SLF001
    any_missing = False
    for _binary, label, installed, hint in get_solver_status():
        if installed:
            mark = _c(col._GREEN, "✓")  # noqa: SLF001
            print(f"  {mark} {label}")
        else:
            mark = _c(col._RED, "✗")  # noqa: SLF001
            print(f"  {mark} {label}  (not found on PATH)")
            any_missing = True

    if any_missing:
        print()
        print(_c(col._YELLOW, "  To install missing open-source solvers:"))  # noqa: SLF001
        for _binary, label, installed, hint in get_solver_status():
            if not installed and hint:
                print(f"    {hint}   # {label}")
        print()
        print(
            "  CPLEX is a commercial solver; download from "
            "https://www.ibm.com/products/ilog-cplex-optimization-studio"
        )
        print("  HiGHS Python: pip install highspy")


# ---------------------------------------------------------------------------
# Interactive first-run setup
# ---------------------------------------------------------------------------


def _prompt(prompt_text: str, default: str = "") -> str:
    """Prompt the user for input, showing a default if provided."""
    if not sys.stdin.isatty():
        return default
    full_prompt = f"{prompt_text} [{default}]: " if default else f"{prompt_text}: "
    try:
        answer = input(full_prompt).strip()
        return answer if answer else default
    except (EOFError, KeyboardInterrupt):
        return default


def run_interactive_setup(config_path: Path, use_color: bool = True) -> dict[str, str]:
    """
    Run the interactive first-run setup wizard.

    Reads the git email as a proposed default, checks solver availability,
    adds AI configuration questions, and writes the resulting config to
    *config_path*.

    Returns the final config dict.
    """

    def _c(code: str, text: str) -> str:
        return f"{code}{text}{col._RESET}" if use_color else text  # noqa: SLF001

    print()
    print(_c(col._BOLD, "─── gtopt_check_lp first-run setup ───"))  # noqa: SLF001
    print(
        "\nThis tool analyzes infeasible LP files generated by gtopt."
        "\nLet's configure it for your system."
    )

    cfg = load_config(config_path)

    # ── Email ──────────────────────────────────────────────────────────────
    git_email = read_git_email()
    current_email = cfg.get("email", "")
    proposed_email = current_email or git_email

    print()
    if git_email and not current_email:
        print(f"  Found git user.email: {_c(col._CYAN, git_email)}")  # noqa: SLF001
    elif current_email:
        print(f"  Current email: {_c(col._CYAN, current_email)}")  # noqa: SLF001

    email = _prompt(
        "  E-mail address (used for NEOS server submissions)", proposed_email
    )
    cfg["email"] = email

    # ── Solver ─────────────────────────────────────────────────────────────
    print()
    print_solver_status(use_color=use_color)

    current_solver = cfg.get("solver", "all")
    solver_choices = ("all", "auto", "cplex", "highs", "coinor", "glpk", "neos")
    solver_hint = "  Preferred solver " + _c(col._CYAN, str(list(solver_choices)))  # noqa: SLF001
    solver = _prompt(solver_hint, current_solver)
    if solver not in solver_choices:
        print(f"  Unknown solver '{solver}', using 'all'")
        solver = "all"
    cfg["solver"] = solver

    # ── Timeout ────────────────────────────────────────────────────────────
    current_timeout = cfg.get("timeout", "120")
    timeout_str = _prompt("  Default solver timeout in seconds", current_timeout)
    try:
        int(timeout_str)
        cfg["timeout"] = timeout_str
    except ValueError:
        print(f"  Invalid timeout '{timeout_str}', keeping {current_timeout}")
        cfg["timeout"] = current_timeout

    # ── Color ──────────────────────────────────────────────────────────────
    current_color = cfg.get("color", "auto")
    color = _prompt("  Color output ('auto', 'always', 'never')", current_color)
    if color not in ("auto", "always", "never"):
        color = "auto"
    cfg["color"] = color

    # ── AI settings ────────────────────────────────────────────────────────
    print()
    print(_c(col._BOLD, "AI diagnostics:"))  # noqa: SLF001
    print(
        "\n  When an API key is available, gtopt_check_lp can send the LP"
        "\n  infeasibility report to an AI provider for an expert diagnosis."
        "\n  Supported providers: " + ", ".join(_AI_PROVIDERS)
    )

    current_ai_enabled = cfg.get("ai_enabled", "true")
    ai_enabled_str = _prompt(
        "  Enable AI diagnostics by default ('true' or 'false')", current_ai_enabled
    )
    if ai_enabled_str.lower() not in ("true", "false", "1", "0", "yes", "no"):
        ai_enabled_str = "true"
    cfg["ai_enabled"] = ai_enabled_str

    current_ai_provider = cfg.get("ai_provider", _AI_DEFAULT_PROVIDER)
    provider_choices_str = _c(col._CYAN, str(list(_AI_PROVIDERS)))  # noqa: SLF001
    ai_provider = _prompt(
        f"  Preferred AI provider {provider_choices_str}", current_ai_provider
    )
    if ai_provider not in _AI_PROVIDERS:
        print(f"  Unknown provider '{ai_provider}', using '{_AI_DEFAULT_PROVIDER}'")
        ai_provider = _AI_DEFAULT_PROVIDER
    cfg["ai_provider"] = ai_provider

    default_model = _AI_DEFAULT_MODEL.get(ai_provider, "")
    current_ai_model = cfg.get("ai_model", "")
    ai_model = _prompt(
        f"  AI model override (leave blank for default: {default_model!r})",
        current_ai_model,
    )
    cfg["ai_model"] = ai_model

    # ── Save ───────────────────────────────────────────────────────────────
    save_config(config_path, cfg)
    print()
    print(f"  {_c(col._GREEN, '✓')} Configuration saved to: {config_path}")  # noqa: SLF001
    print()

    return cfg
