#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
"""
gtopt_check_lp.py — Analyze infeasible LP files generated by gtopt.

When gtopt generates an ``error*.lp`` file due to solver infeasibility, this
tool helps diagnose the cause by performing several complementary analyses:

1. **Static analysis** — parses the LP file directly and reports:
   - Variables with conflicting bounds (lb > ub)
   - Empty or fixed constraints
   - Very large or very small coefficients (numerical range issues)
   - Duplicate constraint names
   - Overall problem statistics

2. **Local IIS finder** — if a supported solver binary is on PATH, runs it to
   find the *Irreducible Infeasible Subsystem* (IIS): the minimal set of
   constraints and bounds that cannot all be satisfied simultaneously.
   Supported solvers (tried in order):
   - CPLEX        (``cplex`` binary)
   - HiGHS        (``highs`` binary or ``highspy`` Python package)
   - COIN-OR CLP  (``clp`` binary — same solver gtopt uses internally)
   - COIN-OR CBC  (``cbc`` binary — CLP + branch-and-cut)
   - GLPK         (``glpsol`` binary)

3. **NEOS server** — if no local solver is available, submits the LP to the
   NEOS online optimization server (https://neos-server.org) using the
   CPLEX LP solver via its XML-RPC API, and waits for the results.

Usage
-----
::

    gtopt-check-lp problem.lp
    gtopt-check-lp problem.lp --analyze-only
    gtopt-check-lp problem.lp --solver coinor
    gtopt-check-lp problem.lp --use-neos --email user@example.com
    gtopt-check-lp problem.lp --output report.txt --verbose

Options
-------
``--analyze-only``
    Perform only the static analysis; do not invoke any solver.

``--solver {auto,cplex,highs,coinor,glpk,neos}``
    Select the IIS/infeasibility solver.  Default: ``auto`` (tries local
    solvers in order: CPLEX → HiGHS → COIN-OR → GLPK, then falls back to
    NEOS if ``--email`` is provided).

``--email EMAIL``
    E-mail address for the NEOS server submission (required for NEOS).

``--solver-url URL``
    XML-RPC endpoint for a NEOS-compatible server.
    Default: ``https://neos-server.org:3333``.

``--timeout SECONDS``
    Maximum time to wait for a solver result (default: 10 s).

``--output FILE``
    Write the full analysis report to *FILE* in addition to stdout.

``--no-color``
    Disable ANSI color codes in the output (auto-detected for non-TTY).

``--verbose``, ``-v``
    Enable verbose / debug logging.

``--version``
    Print the package version and exit.

Exit codes
----------
0 — analysis completed successfully (infeasibility cause may or may not have
    been identified; check the report).
1 — fatal error (file not found, solver crashed, network error, etc.).
"""

import argparse
import logging
import re
import shutil
import subprocess
import sys
import tempfile
import time
import xmlrpc.client
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

try:
    from importlib.metadata import version as _pkg_version, PackageNotFoundError

    try:
        __version__ = _pkg_version("gtopt-scripts")
    except PackageNotFoundError:
        __version__ = "dev"
except ImportError:
    __version__ = "dev"

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# ANSI helpers
# ---------------------------------------------------------------------------

_BOLD = "\033[1m"
_RED = "\033[31m"
_YELLOW = "\033[33m"
_GREEN = "\033[32m"
_CYAN = "\033[36m"
_RESET = "\033[0m"

_USE_COLOR = True  # set by CLI args; module-level for simplicity


def _c(code: str, text: str) -> str:
    return f"{code}{text}{_RESET}" if _USE_COLOR else text


def _header(title: str) -> str:
    line = "─" * (len(title) + 4)
    return f"\n{_c(_BOLD, f'┌{line}┐')}\n{_c(_BOLD, f'│  {title}  │')}\n{_c(_BOLD, f'└{line}┘')}"


# ---------------------------------------------------------------------------
# LP file static analyser
# ---------------------------------------------------------------------------


@dataclass
class VariableBounds:
    """Bounds for one variable parsed from the Bounds section."""

    name: str
    lb: float = 0.0
    ub: float = float("inf")


@dataclass
class LPStats:
    """Statistics and potential issues discovered in an LP file."""

    n_vars: int = 0
    n_constraints: int = 0
    n_integers: int = 0
    n_binary: int = 0
    has_objective: bool = False
    is_minimization: bool = True

    # Numerical range
    max_abs_coeff: float = 0.0
    min_abs_nonzero_coeff: float = float("inf")

    # Issues found
    infeasible_bounds: list[VariableBounds] = field(default_factory=list)
    empty_constraints: list[str] = field(default_factory=list)
    fixed_variables: list[str] = field(default_factory=list)
    duplicate_constraint_names: list[str] = field(default_factory=list)
    large_coeff_constraints: list[str] = field(default_factory=list)
    small_coeff_constraints: list[str] = field(default_factory=list)
    unbounded_variables: list[str] = field(default_factory=list)

    def has_issues(self) -> bool:
        return bool(
            self.infeasible_bounds
            or self.empty_constraints
            or self.duplicate_constraint_names
            or self.large_coeff_constraints
        )


# Coefficient pattern: optional sign + optional number + variable name
_COEFF_RE = re.compile(
    r"([+-]?\s*\d+\.?\d*(?:[eE][+-]?\d+)?)\s*\*?\s*([A-Za-z_][A-Za-z0-9_:.]*)?"
    r"|([+-]?\s*\d+\.?\d*(?:[eE][+-]?\d+)?)"
    r"|([+-]?\s*[A-Za-z_][A-Za-z0-9_:.]*)"
)

_LARGE_COEFF_THRESHOLD = 1e10
_SMALL_COEFF_THRESHOLD = 1e-10


def _parse_coefficients(expr: str) -> list[float]:
    """Extract all numeric coefficients from an LP constraint expression."""
    # Match all numbers (possibly scientific notation)
    return [float(m) for m in re.findall(r"[+-]?\s*\d+\.?\d*(?:[eE][+-]?\d+)?", expr)]


def _strip_comments(line: str) -> str:
    """Remove LP-format comments (text after '\\')."""
    idx = line.find("\\")
    return line[:idx].strip() if idx >= 0 else line.strip()


def analyze_lp_file(lp_path: Path) -> LPStats:  # noqa: PLR0912, PLR0915
    """
    Parse *lp_path* (CPLEX LP format) and return an :class:`LPStats` object
    describing problem statistics and any detected issues.
    """
    stats = LPStats()
    bounds: dict[str, VariableBounds] = {}
    constraint_names: list[str] = []
    all_var_names: set[str] = set()

    try:
        text = lp_path.read_text(encoding="utf-8", errors="replace")
    except OSError as exc:
        raise FileNotFoundError(f"Cannot read LP file: {exc}") from exc

    # ---- Section detection ------------------------------------------------
    section = "preamble"
    current_con_name = ""
    current_con_expr = ""

    sections_start = {
        "minimize": "objective",
        "minimum": "objective",
        "min": "objective",
        "maximize": "objective",
        "maximum": "objective",
        "max": "objective",
        "subject to": "constraints",
        "such that": "constraints",
        "st": "constraints",
        "s.t.": "constraints",
        "bounds": "bounds",
        "bound": "bounds",
        "general": "general",
        "generals": "general",
        "integer": "general",
        "integers": "general",
        "binary": "binary",
        "binaries": "binary",
        "end": "end",
    }

    def _flush_constraint(name: str, expr: str) -> None:
        """Process a completed constraint expression."""
        if not name:
            return
        coeffs = _parse_coefficients(expr.split(":")[1] if ":" in expr else expr)
        if not coeffs:
            stats.empty_constraints.append(name)
        else:
            abs_coeffs = [abs(c) for c in coeffs if c != 0.0]
            if abs_coeffs:
                local_max = max(abs_coeffs)
                local_min = min(abs_coeffs)
                stats.max_abs_coeff = max(stats.max_abs_coeff, local_max)
                if local_min < stats.min_abs_nonzero_coeff:
                    stats.min_abs_nonzero_coeff = local_min
                if local_max >= _LARGE_COEFF_THRESHOLD:
                    stats.large_coeff_constraints.append(name)
                if local_min <= _SMALL_COEFF_THRESHOLD and local_min > 0.0:
                    stats.small_coeff_constraints.append(name)

    # ---- Parse variables mentioned in objective/constraints ---------------
    _VAR_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_:.]*")

    for raw_line in text.splitlines():
        line = _strip_comments(raw_line)
        if not line:
            continue

        lower = line.lower()

        # Check for section header
        matched_section = None
        for key, sec in sections_start.items():
            if lower == key or lower.startswith(key + " ") or lower.startswith(key + ":"):
                matched_section = sec
                break

        if matched_section is not None:
            # Flush pending constraint
            if section == "constraints" and current_con_name:
                _flush_constraint(current_con_name, current_con_expr)
                current_con_name = ""
                current_con_expr = ""
            section = matched_section
            if section == "objective":
                stats.has_objective = True
                stats.is_minimization = "min" in lower
            continue

        if section == "end":
            break

        if section == "objective":
            # Collect variable names
            all_var_names.update(
                v
                for v in _VAR_RE.findall(line)
                if not re.match(r"^[eE]$", v)  # skip exponent markers
            )

        elif section == "constraints":
            # Check for constraint name prefix "name: ..."
            con_match = re.match(r"^\s*([A-Za-z_][A-Za-z0-9_:.()\[\]]*)\s*:", line)
            if con_match:
                # Flush previous constraint
                if current_con_name:
                    _flush_constraint(current_con_name, current_con_expr)
                current_con_name = con_match.group(1)
                current_con_expr = line
                constraint_names.append(current_con_name)
                stats.n_constraints += 1
                # Collect variable names
                all_var_names.update(
                    v
                    for v in _VAR_RE.findall(line)
                    if not re.match(r"^[eE]$", v)
                )
            elif current_con_name:
                # Continuation of current constraint
                current_con_expr += " " + line
                all_var_names.update(
                    v
                    for v in _VAR_RE.findall(line)
                    if not re.match(r"^[eE]$", v)
                )

        elif section == "bounds":
            # Parse "lb <= var <= ub", "var >= lb", "var <= ub",
            #        "-inf <= var <= inf", "var free"
            # Patterns:
            #   number <= var <= number
            #   number <= var
            #   var <= number
            #   var >= number
            #   var free
            line_clean = line.replace(" ", "")
            free_m = re.match(
                r"^([A-Za-z_][A-Za-z0-9_:.]*)>=?-[Ii]nf$", line_clean
            ) or re.match(r"^([A-Za-z_][A-Za-z0-9_:.]*)[Ff]ree$", line_clean)
            if free_m:
                v = free_m.group(1)
                bounds[v] = VariableBounds(name=v, lb=float("-inf"), ub=float("inf"))
                all_var_names.add(v)
                continue

            # lb <= var <= ub
            m = re.match(
                r"^([+-]?[\d.eE+\-]+|[+-]?[Ii]nf)\s*<=?\s*"
                r"([A-Za-z_][A-Za-z0-9_:.]*)\s*<=?\s*"
                r"([+-]?[\d.eE+\-]+|[+-]?[Ii]nf)$",
                line_clean,
                re.IGNORECASE,
            )
            if m:
                v = m.group(2)
                lb_s, ub_s = m.group(1), m.group(3)
                lb = float("-inf") if "inf" in lb_s.lower() else float(lb_s)
                ub = float("inf") if "inf" in ub_s.lower() else float(ub_s)
                bounds[v] = VariableBounds(name=v, lb=lb, ub=ub)
                all_var_names.add(v)
                continue

            # var >= lb
            m2 = re.match(
                r"^([A-Za-z_][A-Za-z0-9_:.]*)\s*>=?\s*"
                r"([+-]?[\d.eE+\-]+|[+-]?[Ii]nf)$",
                line_clean,
                re.IGNORECASE,
            )
            if m2:
                v = m2.group(1)
                lb_s = m2.group(2)
                lb = float("-inf") if "inf" in lb_s.lower() else float(lb_s)
                existing = bounds.get(v, VariableBounds(name=v))
                bounds[v] = VariableBounds(name=v, lb=lb, ub=existing.ub)
                all_var_names.add(v)
                continue

            # var <= ub
            m3 = re.match(
                r"^([A-Za-z_][A-Za-z0-9_:.]*)\s*<=?\s*"
                r"([+-]?[\d.eE+\-]+|[+-]?[Ii]nf)$",
                line_clean,
                re.IGNORECASE,
            )
            if m3:
                v = m3.group(1)
                ub_s = m3.group(2)
                ub = float("inf") if "inf" in ub_s.lower() else float(ub_s)
                existing = bounds.get(v, VariableBounds(name=v))
                bounds[v] = VariableBounds(name=v, lb=existing.lb, ub=ub)
                all_var_names.add(v)
                continue

            # number >= var
            m4 = re.match(
                r"^([+-]?[\d.eE+\-]+|[+-]?[Ii]nf)\s*>=?\s*"
                r"([A-Za-z_][A-Za-z0-9_:.]*)$",
                line_clean,
                re.IGNORECASE,
            )
            if m4:
                v = m4.group(2)
                ub_s = m4.group(1)
                ub = float("inf") if "inf" in ub_s.lower() else float(ub_s)
                existing = bounds.get(v, VariableBounds(name=v))
                bounds[v] = VariableBounds(name=v, lb=existing.lb, ub=ub)
                all_var_names.add(v)
                continue

            # Collect any variable names
            all_var_names.update(
                v
                for v in _VAR_RE.findall(line)
                if not re.match(r"^[eE]$", v)
            )

        elif section == "general":
            stats.n_integers += len(_VAR_RE.findall(line))
            all_var_names.update(_VAR_RE.findall(line))

        elif section == "binary":
            stats.n_binary += len(_VAR_RE.findall(line))
            all_var_names.update(_VAR_RE.findall(line))

    # Flush last constraint
    if section == "constraints" and current_con_name:
        _flush_constraint(current_con_name, current_con_expr)

    # ---- Post-process bounds -----------------------------------------------
    stats.n_vars = len(all_var_names)

    for vb in bounds.values():
        if vb.lb > vb.ub:
            stats.infeasible_bounds.append(vb)
        elif vb.lb == vb.ub:
            stats.fixed_variables.append(vb.name)
        if vb.lb == float("-inf") and vb.ub == float("inf"):
            stats.unbounded_variables.append(vb.name)

    # ---- Duplicate constraint names ----------------------------------------
    seen: set[str] = set()
    for name in constraint_names:
        if name in seen:
            stats.duplicate_constraint_names.append(name)
        seen.add(name)

    # Clamp min_abs_nonzero_coeff to 0.0 if no non-zero coefficients seen
    if stats.min_abs_nonzero_coeff == float("inf"):
        stats.min_abs_nonzero_coeff = 0.0

    return stats


# ---------------------------------------------------------------------------
# Report formatting
# ---------------------------------------------------------------------------


def format_static_report(lp_path: Path, stats: LPStats) -> str:
    """Return a formatted analysis report string."""
    lines = []
    lines.append(_header(f"Static Analysis: {lp_path.name}"))

    # Problem statistics
    lines.append(f"\n{_c(_BOLD, 'Problem statistics')}")
    sense = "Minimization" if stats.is_minimization else "Maximization"
    lines.append(f"  Objective:      {sense}")
    lines.append(f"  Variables:      {stats.n_vars}")
    lines.append(f"  Constraints:    {stats.n_constraints}")
    if stats.n_integers:
        lines.append(f"  Integer vars:   {stats.n_integers}")
    if stats.n_binary:
        lines.append(f"  Binary vars:    {stats.n_binary}")
    if stats.max_abs_coeff > 0:
        lines.append(
            f"  Max |coeff|:    {stats.max_abs_coeff:.3e}"
            + (
                _c(_RED, "  ← very large")
                if stats.max_abs_coeff >= _LARGE_COEFF_THRESHOLD
                else ""
            )
        )
    if stats.min_abs_nonzero_coeff < float("inf") and stats.min_abs_nonzero_coeff > 0:
        lines.append(
            f"  Min |coeff| ≠0: {stats.min_abs_nonzero_coeff:.3e}"
            + (
                _c(_YELLOW, "  ← very small")
                if stats.min_abs_nonzero_coeff <= _SMALL_COEFF_THRESHOLD
                else ""
            )
        )
    coeff_ratio = (
        stats.max_abs_coeff / stats.min_abs_nonzero_coeff
        if stats.min_abs_nonzero_coeff > 0 and stats.max_abs_coeff > 0
        else 0.0
    )
    if coeff_ratio > 1e6:
        lines.append(
            f"  Coeff ratio:    {coeff_ratio:.3e}"
            + _c(_YELLOW, "  ← poor numerical conditioning")
        )

    # Issues
    if not stats.has_issues():
        lines.append(
            f"\n{_c(_GREEN, '✓ No obvious static infeasibilities detected.')}"
        )
    else:
        lines.append(
            f"\n{_c(_BOLD, _c(_RED, '⚠ Potential infeasibility causes:'))}"
        )

        if stats.infeasible_bounds:
            lines.append(
                f"\n  {_c(_RED, f'Conflicting variable bounds ({len(stats.infeasible_bounds)}):')} "
                f"(lb > ub — variable domain is empty)"
            )
            for vb in stats.infeasible_bounds[:20]:
                lines.append(f"    • {vb.name}: lb={vb.lb:g}  >  ub={vb.ub:g}")
            if len(stats.infeasible_bounds) > 20:
                lines.append(
                    f"    … and {len(stats.infeasible_bounds) - 20} more"
                )

        if stats.empty_constraints:
            lines.append(
                f"\n  {_c(_YELLOW, f'Empty constraints ({len(stats.empty_constraints)}):')} "
                f"(no non-zero coefficients)"
            )
            for name in stats.empty_constraints[:10]:
                lines.append(f"    • {name}")
            if len(stats.empty_constraints) > 10:
                lines.append(
                    f"    … and {len(stats.empty_constraints) - 10} more"
                )

        if stats.duplicate_constraint_names:
            lines.append(
                f"\n  {_c(_YELLOW, f'Duplicate constraint names ({len(stats.duplicate_constraint_names)}):')} "
            )
            for name in stats.duplicate_constraint_names[:10]:
                lines.append(f"    • {name}")

        if stats.large_coeff_constraints:
            lines.append(
                f"\n  {_c(_YELLOW, f'Constraints with very large coefficients (≥ {_LARGE_COEFF_THRESHOLD:.0e}):')} "
                f"({len(stats.large_coeff_constraints)} constraints)"
            )
            for name in stats.large_coeff_constraints[:10]:
                lines.append(f"    • {name}")
            if len(stats.large_coeff_constraints) > 10:
                lines.append(
                    f"    … and {len(stats.large_coeff_constraints) - 10} more"
                )

    if stats.fixed_variables:
        lines.append(
            f"\n  {_c(_CYAN, f'Fixed variables ({len(stats.fixed_variables)}):')} (lb == ub)"
        )
        for name in stats.fixed_variables[:10]:
            lines.append(f"    • {name}")
        if len(stats.fixed_variables) > 10:
            lines.append(f"    … and {len(stats.fixed_variables) - 10} more")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Local CPLEX IIS finder
# ---------------------------------------------------------------------------


def _cplex_script(lp_path: Path) -> str:
    """Return CPLEX interactive commands to find and display the IIS."""
    return (
        f"read {lp_path}\n"
        "set preprocessing presolve 0\n"
        "optimize\n"
        "conflict\n"
        "display conflict all\n"
        "quit\n"
    )


def run_local_cplex(lp_path: Path, timeout: int = 120) -> tuple[bool, str]:
    """
    Run the local ``cplex`` binary to find the IIS.

    Returns ``(success, output)`` where *success* is True when CPLEX was
    found and executed without crashing.
    """
    cplex_bin = shutil.which("cplex")
    if cplex_bin is None:
        return False, "cplex binary not found on PATH."

    script = _cplex_script(lp_path)
    log.debug("Running CPLEX from: %s", cplex_bin)

    try:
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".cplex_cmds", delete=False, encoding="utf-8"
        ) as tf:
            tf.write(script)
            script_path = tf.name

        result = subprocess.run(
            [cplex_bin, "-f", script_path],
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
        output = result.stdout + result.stderr
        return True, output
    except subprocess.TimeoutExpired:
        return False, f"CPLEX timed out after {timeout}s."
    except OSError as exc:
        return False, f"Failed to run CPLEX: {exc}"
    finally:
        try:
            Path(script_path).unlink(missing_ok=True)
        except Exception:  # noqa: BLE001
            pass


# ---------------------------------------------------------------------------
# Local HiGHS IIS finder
# ---------------------------------------------------------------------------


def run_local_highs_binary(lp_path: Path, timeout: int = 120) -> tuple[bool, str]:
    """
    Run the ``highs`` binary to solve the LP and report infeasibility info.

    Returns ``(success, output)``.
    """
    highs_bin = shutil.which("highs")
    if highs_bin is None:
        return False, "highs binary not found on PATH."

    log.debug("Running HiGHS from: %s", highs_bin)
    try:
        result = subprocess.run(
            [
                highs_bin,
                "--model_file",
                str(lp_path),
                "--presolve",
                "off",
                "--solver",
                "simplex",
            ],
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
        return True, result.stdout + result.stderr
    except subprocess.TimeoutExpired:
        return False, f"HiGHS timed out after {timeout}s."
    except OSError as exc:
        return False, f"Failed to run HiGHS: {exc}"


def run_local_highs_python(lp_path: Path) -> tuple[bool, str]:
    """
    Use the ``highspy`` Python package to find the IIS (if installed).

    Returns ``(success, output)``.
    """
    try:
        import highspy  # type: ignore[import]  # noqa: PLC0415
    except ImportError:
        return False, "highspy Python package not installed."

    log.debug("Using highspy for IIS analysis")
    lines: list[str] = []
    try:
        h = highspy.Highs()
        h.silent()
        h.readModel(str(lp_path))
        h.run()
        info = h.getInfoValue("primal_solution_status")
        model_status = str(h.getModelStatus())
        lines.append(f"HiGHS model status: {model_status}")

        # Try IIS via conflict analysis (available in highspy >= 1.7)
        try:
            iis = h.getIis()
            lines.append("\n-- HiGHS IIS (Irreducible Infeasible Subsystem) --")
            if hasattr(iis, "col_index") and iis.col_index:
                lines.append(f"  Infeasible variable bounds ({len(iis.col_index)}):")
                for ci in iis.col_index:
                    lines.append(f"    • column index {ci}")
            if hasattr(iis, "row_index") and iis.row_index:
                lines.append(f"  Infeasible constraints ({len(iis.row_index)}):")
                for ri in iis.row_index:
                    lines.append(f"    • row index {ri}")
        except (AttributeError, Exception) as exc:  # noqa: BLE001
            lines.append(f"  IIS not available: {exc}")
            lines.append(f"  Solution status info: {info}")

        return True, "\n".join(lines)
    except Exception as exc:  # noqa: BLE001
        return False, f"highspy error: {exc}"


# ---------------------------------------------------------------------------
# Local COIN-OR (CLP / CBC) infeasibility runner
# ---------------------------------------------------------------------------

# Infeasibility markers produced by CLP / CBC
_COINOR_INFEAS_PATTERNS = [
    re.compile(r"Primal infeasible", re.IGNORECASE),
    re.compile(r"PrimalInfeasible", re.IGNORECASE),
    re.compile(r"Presolve determined that the problem was infeasible", re.IGNORECASE),
    re.compile(r"Analysis indicates model infeasible or unbounded", re.IGNORECASE),
    re.compile(r"bad bound pairs or bad objectives were found", re.IGNORECASE),
    re.compile(r"Linear relaxation infeasible", re.IGNORECASE),
]


def _parse_coinor_infeasibility(output: str) -> list[str]:
    """
    Extract human-readable infeasibility hints from CLP/CBC output.

    Returns a list of matched diagnostic lines (may be empty when the LP is
    feasible or the output contains no recognisable markers).
    """
    findings: list[str] = []
    for line in output.splitlines():
        for pat in _COINOR_INFEAS_PATTERNS:
            if pat.search(line):
                findings.append(line.strip())
                break
    return findings


def run_local_coinor(lp_path: Path, timeout: int = 10) -> tuple[bool, str]:
    """
    Run CLP or CBC (COIN-OR) to analyse the LP file for infeasibility.

    COIN-OR is the solver used by gtopt internally, so it is the most
    natural first check.  It does not have a built-in IIS finder, but it:

    - Confirms infeasibility via presolve or simplex
    - Reports ``bad bound pairs`` when variable bounds conflict
    - Reports the primal infeasibility measure and the number of infeasible
      rows
    - Provides problem statistics via the ``statistics`` command

    The function tries ``clp`` first (pure LP, lighter) and falls back to
    ``cbc`` if ``clp`` is not available.

    Returns ``(success, output)`` where *success* is True when at least one
    COIN-OR binary was found and executed without crashing.
    """
    results: list[str] = []

    for binary_name, extra_args in [
        ("clp", ["statistics", "solve"]),
        ("cbc", ["statistics", "solve"]),
    ]:
        binary = shutil.which(binary_name)
        if binary is None:
            continue

        log.debug("Running COIN-OR %s from: %s", binary_name.upper(), binary)
        try:
            proc = subprocess.run(
                [binary, str(lp_path)] + extra_args,
                capture_output=True,
                text=True,
                timeout=timeout,
                check=False,
            )
            raw = proc.stdout + proc.stderr
            findings = _parse_coinor_infeasibility(raw)

            section_lines = [f"--- {binary_name.upper()} output ---", raw]
            if findings:
                section_lines.insert(1, "\nKey infeasibility findings:")
                section_lines[2:2] = [f"  ✗ {f}" for f in findings]
                section_lines.append("")
            results.append("\n".join(section_lines))

        except subprocess.TimeoutExpired:
            results.append(
                f"--- {binary_name.upper()} ---\n"
                f"{binary_name.upper()} timed out after {timeout}s."
            )
        except OSError as exc:
            log.debug("Failed to run %s: %s", binary_name, exc)
            continue  # try next binary

        # If we got output from this binary, no need to try the next one
        if results:
            break

    if not results:
        return False, "Neither clp nor cbc binary found on PATH."

    return True, "\n\n".join(results)


# ---------------------------------------------------------------------------
# Local GLPK IIS helper
# ---------------------------------------------------------------------------


def run_local_glpk(lp_path: Path, timeout: int = 120) -> tuple[bool, str]:
    """
    Run ``glpsol`` (GLPK) to attempt LP analysis.

    GLPK does not support IIS finding directly, but the output helps confirm
    the infeasibility and may hint at which constraints are involved via
    sensitivity analysis.

    Returns ``(success, output)``.
    """
    glpsol_bin = shutil.which("glpsol")
    if glpsol_bin is None:
        return False, "glpsol binary not found on PATH."

    log.debug("Running GLPK from: %s", glpsol_bin)
    try:
        result = subprocess.run(
            [glpsol_bin, "--lp", str(lp_path), "--ranges", "/dev/null"],
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
        return True, result.stdout + result.stderr
    except subprocess.TimeoutExpired:
        return False, f"glpsol timed out after {timeout}s."
    except OSError as exc:
        return False, f"Failed to run glpsol: {exc}"


# ---------------------------------------------------------------------------
# NEOS XML-RPC client
# ---------------------------------------------------------------------------

_NEOS_DEFAULT_URL = "https://neos-server.org:3333"

_NEOS_LP_CPLEX_XML = """\
<document>
<category>lp</category>
<solver>CPLEX</solver>
<inputMethod>LP</inputMethod>
<client>gtopt-check-lp</client>
<email>{email}</email>
<LP><![CDATA[
{lp_content}
]]></LP>
<commands><![CDATA[
conflict
display conflict all
]]></commands>
<comment><![CDATA[
LP infeasibility analysis submitted by gtopt-check-lp {version}
]]></comment>
</document>
"""


class NeosClient:
    """
    Client for the NEOS optimization server XML-RPC API.

    See https://neos-server.org/neos/xml-rpc.html for the API reference.
    """

    def __init__(self, url: str = _NEOS_DEFAULT_URL, timeout: int = 10) -> None:
        self.url = url
        self.timeout = timeout
        self._proxy: Optional[xmlrpc.client.ServerProxy] = None

    def _get_proxy(self) -> xmlrpc.client.ServerProxy:
        if self._proxy is None:
            self._proxy = xmlrpc.client.ServerProxy(self.url)
        return self._proxy

    def ping(self) -> bool:
        """Return True if the NEOS server is reachable."""
        try:
            msg = self._get_proxy().ping()
            return "NEOS" in str(msg)
        except Exception:  # noqa: BLE001
            return False

    def submit_lp(
        self, lp_path: Path, email: str
    ) -> tuple[Optional[int], Optional[str]]:
        """
        Submit an LP file to NEOS.

        Returns ``(job_number, password)`` or ``(None, error_message)``.
        """
        lp_content = lp_path.read_text(encoding="utf-8", errors="replace")
        xml = _NEOS_LP_CPLEX_XML.format(
            email=email,
            lp_content=lp_content,
            version=__version__,
        )
        try:
            proxy = self._get_proxy()
            result = proxy.submitJob(xml)
            if isinstance(result, (list, tuple)) and len(result) == 2:
                job_number, password = result
                if isinstance(job_number, int) and job_number > 0:
                    return job_number, password
                return None, f"NEOS returned error: {result}"
            return None, f"Unexpected NEOS response: {result}"
        except xmlrpc.client.Fault as exc:
            return None, f"NEOS XML-RPC fault: {exc}"
        except OSError as exc:
            return None, f"Network error connecting to {self.url}: {exc}"

    def wait_for_result(
        self,
        job_number: int,
        password: str,
        poll_interval: float = 5.0,
    ) -> tuple[bool, str]:
        """
        Poll until the NEOS job completes and return ``(success, output)``.
        """
        proxy = self._get_proxy()
        deadline = time.monotonic() + self.timeout
        last_status = ""

        while time.monotonic() < deadline:
            try:
                status = str(proxy.getJobStatus(job_number, password))
            except Exception as exc:  # noqa: BLE001
                return False, f"Error polling NEOS: {exc}"

            if status != last_status:
                log.info("NEOS job %d: %s", job_number, status)
                last_status = status

            if status == "Done":
                try:
                    raw = proxy.getFinalResults(job_number, password)
                    # getFinalResults may return bytes or a Binary object
                    if hasattr(raw, "data"):
                        output = raw.data.decode("utf-8", errors="replace")
                    elif isinstance(raw, bytes):
                        output = raw.decode("utf-8", errors="replace")
                    else:
                        output = str(raw)
                    return True, output
                except Exception as exc:  # noqa: BLE001
                    return False, f"Error retrieving NEOS results: {exc}"

            if status in ("Error", "Unknown"):
                return False, f"NEOS job {job_number} ended with status: {status}"

            time.sleep(poll_interval)

        return False, f"Timed out waiting for NEOS job {job_number} after {self.timeout}s."

    def submit_and_wait(
        self, lp_path: Path, email: str, poll_interval: float = 5.0
    ) -> tuple[bool, str]:
        """
        Submit an LP to NEOS and wait for the result.

        Returns ``(success, output)``.
        """
        if not self.ping():
            return (
                False,
                f"Cannot reach NEOS server at {self.url}. "
                "Check your internet connection.",
            )

        print(f"  Submitting to NEOS ({self.url}) …")
        job_number, password_or_err = self.submit_lp(lp_path, email)
        if job_number is None:
            return False, str(password_or_err)

        print(f"  NEOS job {job_number} submitted.  Waiting for results …")
        return self.wait_for_result(
            job_number, str(password_or_err), poll_interval=poll_interval
        )


# ---------------------------------------------------------------------------
# Auto-detect available local solvers
# ---------------------------------------------------------------------------


def _detect_local_solvers() -> list[str]:
    """Return names of local solvers that are available on PATH."""
    available = []
    for name, binary in [("CPLEX", "cplex"), ("HiGHS", "highs"), ("GLPK", "glpsol")]:
        if shutil.which(binary):
            available.append(name)
    try:
        import highspy  # type: ignore[import]  # noqa: F401, PLC0415

        if "HiGHS" not in available:
            available.append("HiGHS (Python)")
    except ImportError:
        pass
    return available


# ---------------------------------------------------------------------------
# IIS runner dispatcher
# ---------------------------------------------------------------------------


def run_iis(
    lp_path: Path,
    solver: str,
    email: str,
    neos_url: str,
    timeout: int,
) -> Optional[tuple[bool, str, str]]:
    """
    Try to find the IIS using the requested strategy.

    Returns ``(success, solver_name, output)`` or None if no solver was tried.
    """
    solver_lower = solver.lower()
    tried: list[tuple[str, Any]] = []

    def _try_cplex() -> Optional[tuple[bool, str, str]]:
        ok, out = run_local_cplex(lp_path, timeout=timeout)
        return (ok, "CPLEX (local)", out)

    def _try_highs() -> Optional[tuple[bool, str, str]]:
        # Prefer Python bindings (more info) over binary
        ok, out = run_local_highs_python(lp_path)
        if ok:
            return (ok, "HiGHS (Python)", out)
        ok, out = run_local_highs_binary(lp_path, timeout=timeout)
        return (ok, "HiGHS (binary)", out)

    def _try_glpk() -> Optional[tuple[bool, str, str]]:
        ok, out = run_local_glpk(lp_path, timeout=timeout)
        return (ok, "GLPK", out)

    def _try_neos() -> Optional[tuple[bool, str, str]]:
        if not email:
            return (
                False,
                "NEOS",
                "An e-mail address is required for NEOS. Use --email <address>.",
            )
        client = NeosClient(url=neos_url, timeout=timeout)
        ok, out = client.submit_and_wait(lp_path, email)
        return (ok, "NEOS (CPLEX)", out)

    if solver_lower == "cplex":
        return _try_cplex()
    if solver_lower == "highs":
        return _try_highs()
    if solver_lower == "glpk":
        return _try_glpk()
    if solver_lower == "neos":
        return _try_neos()

    # auto: try local solvers in order, fall back to NEOS
    for label, fn in [("CPLEX", _try_cplex), ("HiGHS", _try_highs), ("GLPK", _try_glpk)]:
        ok, solver_name, out = fn()
        if ok:
            return (True, solver_name, out)
        tried.append((label, out))

    # Fall back to NEOS
    if email:
        return _try_neos()

    # No solver found and no email provided
    tried_msg = "\n".join(f"  {n}: {o}" for n, o in tried)
    return (
        False,
        "none",
        f"No local solver found and --email not provided for NEOS.\n{tried_msg}",
    )


# ---------------------------------------------------------------------------
# High-level analysis entry point
# ---------------------------------------------------------------------------


def check_lp(
    lp_path: Path,
    *,
    analyze_only: bool = False,
    solver: str = "auto",
    email: str = "",
    neos_url: str = _NEOS_DEFAULT_URL,
    timeout: int = 10,
    output_file: Optional[Path] = None,
) -> int:
    """
    Run the full infeasibility analysis pipeline on *lp_path*.

    Returns 0 on success, 1 on error.
    """
    if not lp_path.exists():
        print(_c(_RED, f"Error: file not found: {lp_path}"), file=sys.stderr)
        return 1

    report_parts: list[str] = []

    # 1 ── Static analysis ──────────────────────────────────────────────────
    print(f"\nAnalyzing: {_c(_BOLD, str(lp_path))}")
    print("  Running static analysis …")

    try:
        stats = analyze_lp_file(lp_path)
    except FileNotFoundError as exc:
        print(_c(_RED, f"Error: {exc}"), file=sys.stderr)
        return 1

    static_report = format_static_report(lp_path, stats)
    print(static_report)
    report_parts.append(static_report)

    if analyze_only:
        if output_file:
            _write_report(output_file, report_parts)
        return 0

    # 2 ── IIS / solver analysis ────────────────────────────────────────────
    available = _detect_local_solvers()
    if available:
        print(f"\n  Available local solvers: {', '.join(available)}")
    else:
        print("\n  No local solvers found on PATH.")

    if solver != "auto" or available or email:
        print(f"\n  Running IIS analysis (solver={solver}) …")
        result = run_iis(lp_path, solver, email, neos_url, timeout)
        if result is not None:
            ok, solver_name, out = result
            iis_report = _format_iis_report(solver_name, ok, out)
            print(iis_report)
            report_parts.append(iis_report)
        else:
            msg = "  (No IIS analysis performed.)"
            print(msg)
            report_parts.append(msg)
    else:
        hint = (
            f"\n{_c(_YELLOW, 'Tip:')} "
            "Install a local solver (CPLEX, HiGHS, or GLPK) or provide\n"
            "  --email <address> to submit to the NEOS server for IIS analysis."
        )
        print(hint)
        report_parts.append(hint)

    if output_file:
        _write_report(output_file, report_parts)

    return 0


def _format_iis_report(solver_name: str, success: bool, output: str) -> str:
    """Format the solver IIS output into a readable report section."""
    lines = [_header(f"IIS Analysis ({solver_name})")]
    if not success:
        lines.append(f"\n{_c(_RED, 'Solver error:')} {output}")
    else:
        lines.append(output)
    return "\n".join(lines)


def _write_report(output_file: Path, parts: list[str]) -> None:
    """Write the full report (with ANSI codes stripped) to *output_file*."""
    # Strip ANSI escape codes
    ansi_re = re.compile(r"\033\[[0-9;]*m")
    content = "\n\n".join(parts)
    content = ansi_re.sub("", content)
    try:
        output_file.write_text(content + "\n", encoding="utf-8")
        print(f"\nReport written to: {output_file}")
    except OSError as exc:
        print(f"Warning: could not write report: {exc}", file=sys.stderr)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="gtopt-check-lp",
        description=(
            "Analyze an infeasible LP file generated by gtopt.\n\n"
            "Performs static analysis (bound conflicts, empty constraints,\n"
            "numerical range) and optionally finds the IIS using a local\n"
            "solver (CPLEX, HiGHS, GLPK) or the NEOS online server."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  gtopt-check-lp error_0.lp\n"
            "  gtopt-check-lp error_0.lp --analyze-only\n"
            "  gtopt-check-lp error_0.lp --solver highs\n"
            "  gtopt-check-lp error_0.lp --solver neos --email user@example.com\n"
            "  gtopt-check-lp error_0.lp --output report.txt\n"
        ),
    )

    parser.add_argument("lp_file", metavar="LP_FILE", help="Path to the LP file.")

    parser.add_argument(
        "--analyze-only",
        action="store_true",
        default=False,
        help="Perform only static analysis; do not invoke any solver.",
    )

    parser.add_argument(
        "--solver",
        default="auto",
        choices=["auto", "cplex", "highs", "glpk", "neos"],
        help=(
            "IIS solver to use.  'auto' tries local solvers first, "
            "then NEOS (default: auto)."
        ),
    )

    parser.add_argument(
        "--email",
        default="",
        metavar="EMAIL",
        help="E-mail address for NEOS server submissions (required for NEOS).",
    )

    parser.add_argument(
        "--solver-url",
        default=_NEOS_DEFAULT_URL,
        metavar="URL",
        help=(
            f"XML-RPC endpoint for a NEOS-compatible server "
            f"(default: {_NEOS_DEFAULT_URL})."
        ),
    )

    parser.add_argument(
        "--timeout",
        type=int,
        default=10,
        metavar="SECONDS",
        help="Maximum time to wait for a solver result (default: 10 s).",
    )

    parser.add_argument(
        "--output",
        default=None,
        metavar="FILE",
        help="Write the analysis report to FILE (ANSI codes stripped).",
    )

    parser.add_argument(
        "--no-color",
        action="store_true",
        default=False,
        help="Disable ANSI color codes in terminal output.",
    )

    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        default=False,
        help="Enable verbose / debug logging.",
    )

    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {__version__}",
    )

    return parser


def main(argv: Optional[list[str]] = None) -> int:
    """CLI entry point.  Returns the exit code."""
    parser = _build_parser()
    args = parser.parse_args(argv)

    # Configure logging
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.WARNING,
        format="%(levelname)s: %(message)s",
    )

    # Configure color output
    global _USE_COLOR  # noqa: PLW0603
    _USE_COLOR = not args.no_color and sys.stdout.isatty()

    lp_path = Path(args.lp_file)
    output_file = Path(args.output) if args.output else None

    return check_lp(
        lp_path,
        analyze_only=args.analyze_only,
        solver=args.solver,
        email=args.email,
        neos_url=args.solver_url,
        timeout=args.timeout,
        output_file=output_file,
    )


if __name__ == "__main__":
    sys.exit(main())
