#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
"""
gtopt_check_lp -- Analyze infeasible LP files generated by gtopt.

When gtopt generates an ``error*.lp`` file due to solver infeasibility, this
tool helps diagnose the cause by performing several complementary analyses:

1. **Static analysis** -- parses the LP file directly and reports:
   - Variables with conflicting bounds (lb > ub)
   - Empty or fixed constraints
   - Very large or very small coefficients (numerical range issues)
   - Duplicate constraint names
   - Overall problem statistics

2. **Local IIS finder** -- if a supported solver binary is on PATH, runs it to
   find the *Irreducible Infeasible Subsystem* (IIS).
   Supported solvers (tried in order):
   - CPLEX        (``cplex`` binary -- uses ``tools conflict`` command)
   - HiGHS        (``highs`` binary or ``highspy`` Python package)
   - COIN-OR CLP  (``clp`` binary -- same solver gtopt uses internally)
   - COIN-OR CBC  (``cbc`` binary)

3. **NEOS server** -- if no local solver is available and an e-mail is
   configured, submits the LP to the NEOS online optimization server
   (https://neos-server.org) using CPLEX via its XML-RPC API, and waits
   for the conflict-analysis results.

Configuration
-------------
User preferences are stored in the unified ``~/.gtopt.conf`` (INI format).
AI settings live in the ``[global]`` section (shared with other gtopt tools);
tool-specific settings (email, solver, timeout) live in the
``[gtopt_check_lp]`` section.

On the first run the tool will prompt for these values interactively (when
stdin is a TTY) and suggest solver installation commands for any missing
open-source solvers.

Run ``gtopt_check_lp --init-config`` at any time to create or update the
configuration file.

**Migration**: if ``~/.gtopt_check_lp.conf`` exists and ``~/.gtopt.conf``
does not, settings are migrated automatically on first use.

Quiet mode (``--quiet``)
------------------------
In quiet mode the tool:

* **Never fails** -- always exits with code 0.
* **Never prompts** -- skips the interactive first-run setup wizard even when
  no config file is present; prints a warning instead.
* **Tries every available solver** -- uses all local solvers, then falls back
  to NEOS if an e-mail is configured.  If neither is available it prints a
  warning with installation hints.
* **Handles NEOS gracefully** -- if NEOS is unreachable or returns an error,
  prints a warning and continues with the static-analysis results.
* **Handles AI gracefully** -- if the AI provider is not configured or the
  call fails, prints a warning and continues.

Quiet mode is used by the ``gtopt`` binary to run the diagnostic after an
infeasibility event without risking a stall or a non-zero exit code.

Usage
-----
::

    gtopt_check_lp problem.lp
    gtopt_check_lp problem.lp.gz             # gzip-compressed LP file
    gtopt_check_lp problem.lp.gzip           # alternative gzip extension
    gtopt_check_lp --last                       # auto-find newest error*.lp[.gz]
    gtopt_check_lp problem.lp --analyze-only
    gtopt_check_lp problem.lp --quiet           # non-failing, used by gtopt
    gtopt_check_lp problem.lp --solver coinor
    gtopt_check_lp problem.lp --no-neos --solver coinor
    gtopt_check_lp problem.lp --email user@example.com
    gtopt_check_lp problem.lp --output report.txt --verbose
    gtopt_check_lp --init-config                # create/update config file
"""

from __future__ import annotations

import logging
import sys
from pathlib import Path
from typing import Optional

# ---------------------------------------------------------------------------
# Sub-module imports
# ---------------------------------------------------------------------------

from . import _colors as _col
from ._ai import (
    AiOptions,
    _AI_DEFAULT_PROVIDER,
    _AI_INFEASIBILITY_PROMPT,
    query_ai,
)
from ._benchmark import (
    format_benchmark_table,
    run_benchmark,
)
from ._checker import (
    _find_latest_error_lp,
    _format_iis_report,
    _write_report,
)
from ._cli import _build_parser
from ._compress import is_compressed, resolve_lp_path
from ._config import (
    default_config_path,
    get_solver_status,
    load_config,
    print_solver_status,
    read_git_email,
    run_interactive_setup,
    save_config,
)
from ._lp_analyzer import (
    analyze_lp_file,
    format_static_report,
)
from ._neos import (
    NeosClient,  # noqa: F401  (re-exported for tests / backward compat)
    _NEOS_DEFAULT_URL,
    _NEOS_LP_CPLEX_XML,  # noqa: F401  (re-exported for tests)
)
from ._solvers import (
    _parse_coinor_infeasibility,  # noqa: F401  (re-exported for tests)
    detect_local_solvers,
    run_iis,
    run_local_coinor,  # noqa: F401  (re-exported for tests)
    run_local_cplex,  # noqa: F401  (re-exported for tests)
    run_local_highs_binary,  # noqa: F401  (re-exported for tests)
    run_all_solvers as _run_all_solvers,
)

log = logging.getLogger(__name__)

# Public symbols re-exported for backward compatibility with existing code that
# imports directly from `gtopt_check_lp.gtopt_check_lp`.
__all__ = [
    "AiOptions",
    "NeosClient",
    "_AI_DEFAULT_PROVIDER",
    "_AI_INFEASIBILITY_PROMPT",
    "_NEOS_LP_CPLEX_XML",
    "_build_parser",
    "_parse_coinor_infeasibility",
    "analyze_lp_file",
    "check_lp",
    "format_static_report",
    "main",
    "query_ai",
    "run_all_solvers",
    "run_local_coinor",
    "run_local_cplex",
    "run_local_highs_binary",
]

# ---------------------------------------------------------------------------
# Backward-compatible aliases for the monolithic public names
# ---------------------------------------------------------------------------

_default_config_path = default_config_path
_load_config = load_config
_save_config = save_config
_read_git_email = read_git_email
_get_solver_status = get_solver_status


def run_all_solvers(
    lp_path: Path,
    email: str,
    neos_url: str,
    timeout: int,
) -> tuple[bool, str, str]:
    """Run every available solver; return ``(any_success, "all", output)``."""
    return _run_all_solvers(lp_path, email=email, neos_url=neos_url, timeout=timeout)


# ---------------------------------------------------------------------------
# ANSI helpers (backward-compat module-level names)
# ---------------------------------------------------------------------------

_BOLD = _col._BOLD  # noqa: SLF001
_RED = _col._RED  # noqa: SLF001
_YELLOW = _col._YELLOW  # noqa: SLF001
_GREEN = _col._GREEN  # noqa: SLF001
_CYAN = _col._CYAN  # noqa: SLF001
_RESET = _col._RESET  # noqa: SLF001

_USE_COLOR = True  # written by main() before any output


def _c(code: str, text: str) -> str:
    return f"{code}{text}{_RESET}" if _USE_COLOR else text


def _header(title: str) -> str:
    return _col.header(title)


# ---------------------------------------------------------------------------
# AI diagnostics helper
# ---------------------------------------------------------------------------


def _run_ai_diagnostics(
    report_parts: list[str],
    *,
    provider: str,
    model: Optional[str],
    prompt_template: str,
    api_key: Optional[str],
    timeout: int,
) -> None:
    """Call the AI provider with the combined report and print the response."""
    full_report = "\n\n".join(report_parts)
    print(f"\n  Querying AI provider ({provider}) for diagnostics \u2026")
    ok, response = query_ai(
        full_report,
        provider=provider,
        model=model,
        prompt_template=prompt_template,
        api_key=api_key,
        timeout=timeout,
    )
    ai_section = _header(f"AI Diagnostics ({provider})")
    if not ok:
        msg = f"\n{_c(_YELLOW, 'AI diagnostic unavailable:')} {response}"
        print(msg)
        report_parts.append(ai_section + msg)
    else:
        print(f"\n{ai_section}")
        print(response)
        report_parts.append(f"{ai_section}\n{response}")


# ---------------------------------------------------------------------------
# High-level analysis entry point
# ---------------------------------------------------------------------------


def check_lp(  # pylint: disable=too-many-arguments
    lp_path: Path,
    *,
    analyze_only: bool = False,
    solver: str = "all",
    algo: str = "",
    optimal_eps: float = 0.0,
    feasible_eps: float = 0.0,
    barrier_eps: float = 0.0,
    email: str = "",
    neos_url: str = _NEOS_DEFAULT_URL,
    timeout: int = 5,
    output_file: Optional[Path] = None,
    ai: Optional[AiOptions] = None,
    quiet: bool = False,
    no_neos: bool = False,
    full: bool = False,
) -> int:
    """
    Run the full infeasibility analysis pipeline on *lp_path*.

    Parameters
    ----------
    lp_path:
        Path to the LP file to analyze.  Plain ``.lp`` files and
        gzip-compressed ``.lp.gz`` / ``.lp.gzip`` files are both accepted.
        When the exact path does not exist, the function automatically tries
        ``lp_path + ".gz"`` and ``lp_path + ".gzip"`` as fallbacks.
    analyze_only:
        When True, perform only static analysis (no solver invocation).
    solver:
        Solver strategy: ``"all"``, ``"auto"``, ``"cplex"``, ``"highs"``,
        ``"coinor"``, or ``"neos"``.
    algo:
        LP algorithm to use for COIN-OR and CPLEX solvers.  One of
        ``"default"``, ``"primal"``, ``"dual"``, ``"barrier"``, or ``""``
        (empty string means use the solver-specific default, which is
        ``"barrier"`` for COIN-OR and CPLEX).
    optimal_eps:
        Optimality (dual) tolerance for COIN-OR and CPLEX.  0.0 means use
        the solver's built-in default.  Passed by the gtopt binary to match
        the tolerance settings used in the original solve.
    feasible_eps:
        Feasibility (primal) tolerance for COIN-OR and CPLEX.  0.0 means use
        the solver's built-in default.
    barrier_eps:
        Barrier convergence tolerance for COIN-OR and CPLEX.  0.0 means use
        the solver's built-in default.
    email:
        E-mail address for NEOS submissions.
    neos_url:
        NEOS XML-RPC endpoint.
    timeout:
        Maximum seconds to wait for any local/NEOS solver (default 5).
    output_file:
        If set, write the full report to this file (ANSI codes stripped).
    ai:
        :class:`AiOptions` controlling the optional AI diagnostics step.
        ``None`` is equivalent to ``AiOptions()`` (enabled, Claude).
    quiet:
        When True, the function **never fails**: it always returns 0.
        In quiet mode:

        * Missing or unreadable LP files (including decompression errors)
          produce a warning instead of an error, and the function returns 0.
        * The solver analysis step always runs (even when ``solver="auto"``
          and no local solvers are available).
        * If local solvers are unavailable and *email* is configured, NEOS
          is tried automatically.  NEOS failures (unreachable, timeout, or
          missing e-mail) produce a warning rather than an error.
        * AI failures produce a warning rather than an exception.
        * Static-analysis exceptions produce a warning and return 0.
    no_neos:
        When True, skip NEOS submissions even if an e-mail is configured.

    Returns
    -------
    0 on success (or always in quiet mode), 1 on fatal error.
    """
    ai_opts = ai if ai is not None else AiOptions()

    # Suppress NEOS by clearing the email when requested.  Using a local
    # variable avoids shadowing the caller's `email` parameter.
    filtered_email = "" if no_neos else email

    # Resolve LP path: if the given path doesn't exist, try .gz / .gzip
    # compressed variants automatically.
    resolved = resolve_lp_path(lp_path)
    if resolved is None:
        if quiet:
            print(
                _c(_YELLOW, f"Warning: LP file not found: {lp_path}"),
                file=sys.stderr,
            )
            return 0
        print(_c(_RED, f"Error: file not found: {lp_path}"), file=sys.stderr)
        return 1

    # Tell the user when we resolved to a different (compressed) path.
    if resolved != lp_path:
        print(
            _c(_YELLOW, f"Note: {lp_path} not found; using {resolved}"),
        )
    lp_path = resolved

    # Validate that the resolved path is actually readable.
    if not lp_path.exists():
        if quiet:
            print(
                _c(_YELLOW, f"Warning: LP file not found: {lp_path}"),
                file=sys.stderr,
            )
            return 0
        print(_c(_RED, f"Error: file not found: {lp_path}"), file=sys.stderr)
        return 1

    report_parts: list[str] = []

    # Show a note when the file is compressed.
    compression_note = ""
    if is_compressed(lp_path):
        compression_note = _c(_CYAN, " [compressed]")

    # 1 -- Static analysis ────────────────────────────────────��───────────────
    print(f"\nAnalyzing: {_c(_BOLD, str(lp_path))}{compression_note}")
    print("  Running static analysis \u2026")

    stats = None
    try:
        stats = analyze_lp_file(lp_path)
    except Exception as exc:  # noqa: BLE001  # pylint: disable=broad-exception-caught
        # `except Exception` does NOT catch KeyboardInterrupt/SystemExit.
        if quiet:
            print(
                _c(_YELLOW, f"Warning: static analysis failed: {exc}"),
                file=sys.stderr,
            )
            # Continue to IIS / solver analysis instead of returning early.
        else:
            print(_c(_RED, f"Error: {exc}"), file=sys.stderr)
            return 1

    if stats is not None:
        static_report = format_static_report(lp_path, stats)
        print(static_report)
        report_parts.append(static_report)

    # Flush so the parent process receives output even if we are killed by
    # an external timeout wrapper (e.g. the gtopt binary's spawn_tool).
    sys.stdout.flush()

    if analyze_only:
        if output_file:
            _write_report(output_file, report_parts)
        return 0

    # 2 -- IIS / solver analysis ───��──────────────────────────────────────────
    available = detect_local_solvers()
    if available:
        print(f"\n  Available local solvers: {', '.join(available)}")
    else:
        print("\n  No local solvers found on PATH.")

    # Determine whether to run the solver step.
    # Quiet mode always runs it so the user gets whatever analysis is possible.
    run_solver_step = quiet or solver != "auto" or available or filtered_email

    if run_solver_step:
        print(f"\n  Running solver analysis (solver={solver}) \u2026")

        # In quiet mode, catch any unexpected exception from the solver layer.
        # Note: `except Exception` does NOT catch KeyboardInterrupt/SystemExit
        # (they are BaseException subclasses), so Ctrl-C still terminates the
        # process even in quiet mode.
        try:
            ok, solver_name, out = run_iis(
                lp_path,
                solver=solver,
                algo=algo,
                optimal_eps=optimal_eps,
                feasible_eps=feasible_eps,
                barrier_eps=barrier_eps,
                email=filtered_email,
                neos_url=neos_url,
                timeout=timeout,
            )
        except Exception as exc:  # noqa: BLE001  # pylint: disable=broad-exception-caught
            if quiet:
                ok, solver_name, out = (
                    False,
                    "error",
                    f"Solver error: {exc}",
                )
            else:
                raise

        screen_report, ai_report = _format_iis_report(solver_name, ok, out, full=full)
        print(screen_report)
        report_parts.append(ai_report)

        # Quiet mode: when no local solver and no NEOS email, give targeted
        # advice.
        if quiet and not available and not filtered_email:
            neos_hint = (
                f"\n{_c(_YELLOW, 'Note (quiet mode):')} "
                "No local solvers found and NEOS e-mail is not configured.\n"
                "  The static analysis above may still pinpoint the issue.\n"
                "  To enable IIS analysis:\n"
                "    \u2022 Install a local solver:  "
                "sudo apt install coinor-clp coinor-cbc\n"
                "    \u2022 Or set a NEOS e-mail:    "
                "gtopt_check_lp --init-config"
            )
            print(neos_hint)
            report_parts.append(neos_hint)
    else:
        hint = (
            f"\n{_c(_YELLOW, 'Tip:')} "
            "Install a local solver (CPLEX, HiGHS, or CLP/CBC) or provide\n"
            "  --email <address> to submit to the NEOS server for IIS "
            "analysis.\n"
            "  CLP/CBC (coinor-clp / coinor-cbc) are usually available on\n"
            "  systems where gtopt is installed: "
            "sudo apt install coinor-clp coinor-cbc"
        )
        print(hint)
        report_parts.append(hint)

    # Flush after solver analysis so the parent process receives the complete
    # static + solver output even if the AI step below hangs or is killed.
    sys.stdout.flush()

    # 3 -- AI diagnostics ────────��───────────────────────────���────────────────
    if ai_opts.enabled:
        try:
            _run_ai_diagnostics(
                report_parts,
                provider=ai_opts.provider,
                model=ai_opts.model or None,
                prompt_template=ai_opts.prompt or _AI_INFEASIBILITY_PROMPT,
                api_key=ai_opts.key or None,
                timeout=ai_opts.timeout,
            )
        except Exception as exc:  # noqa: BLE001  # pylint: disable=broad-exception-caught
            if quiet:
                print(
                    _c(
                        _YELLOW,
                        f"  Warning: AI diagnostics failed: {exc}",
                    ),
                    file=sys.stderr,
                )
            else:
                raise

    if output_file:
        _write_report(output_file, report_parts)

    return 0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: Optional[list[str]] = None) -> int:
    """CLI entry point.  Returns the exit code."""
    global _USE_COLOR  # noqa: PLW0603

    parser = _build_parser()
    args = parser.parse_args(argv)

    # -- Config file path ------------------------------------------------------
    config_path = Path(args.config) if args.config else _default_config_path()

    # -- Logging ---------------------------------------------------------------
    log_level = args.log_level or ("DEBUG" if args.verbose else "WARNING")
    logging.basicConfig(
        level=getattr(logging, log_level),
        format="%(levelname)s: %(message)s",
    )

    # -- --init-config: run wizard and exit ------------------------------------
    if args.init_config:
        _USE_COLOR = not args.no_color and sys.stdout.isatty()
        _col.USE_COLOR = _USE_COLOR
        run_interactive_setup(config_path, use_color=_USE_COLOR)
        return 0

    # -- Load config -----------------------------------------------------------
    config_exists = config_path.exists()
    cfg = load_config(config_path)

    # -- Color (resolve before any output) -------------------------------------
    color_setting = cfg.get("color", "auto")
    if args.no_color or color_setting == "never":
        _USE_COLOR = False
    elif color_setting == "always":
        _USE_COLOR = True
    else:
        _USE_COLOR = sys.stdout.isatty()
    _col.USE_COLOR = _USE_COLOR

    # -- First-run setup -------------------------------------------------------
    # Quiet mode always skips interactive setup (it must never block).
    skip_setup = args.no_setup or args.quiet
    if not config_exists and not skip_setup and sys.stdin.isatty():
        print(_c(_YELLOW, f"No config file found at {config_path}."))
        print("Running first-time setup\u2026")
        cfg = run_interactive_setup(config_path, use_color=_USE_COLOR)
    elif not config_exists and args.quiet:
        print(
            _c(
                _YELLOW,
                f"Warning: no config file at {config_path}; "
                "using defaults (quiet mode).",
            ),
            file=sys.stderr,
        )

    # -- --show-config ---------------------------------------------------------
    if args.show_config:
        print(_c(_BOLD, f"\nActive configuration ({config_path}):"))
        for key, val in cfg.items():
            print(f"  {key} = {val!r}")
        print_solver_status(use_color=_USE_COLOR)
        return 0

    # -- Merge CLI overrides into effective config -----------------------------
    effective_email = args.email if args.email is not None else cfg.get("email", "")
    effective_solver = (
        args.solver if args.solver is not None else cfg.get("solver", "auto")
    )
    effective_timeout = (
        args.timeout if args.timeout is not None else int(cfg.get("timeout", "5"))
    )
    effective_neos_url = (
        args.solver_url
        if args.solver_url is not None
        else cfg.get("neos_url", _NEOS_DEFAULT_URL)
    )

    # -- AI settings -----------------------------------------------------------
    cfg_ai_enabled = cfg.get("ai_enabled", "true").lower() not in (
        "false",
        "0",
        "no",
    )
    effective_ai_enabled = (
        args.ai_enabled if args.ai_enabled is not None else cfg_ai_enabled
    )
    effective_ai_provider = (
        args.ai_provider
        if args.ai_provider is not None
        else cfg.get("ai_provider", _AI_DEFAULT_PROVIDER)
    )
    effective_ai_model = (
        args.ai_model if args.ai_model is not None else cfg.get("ai_model", "")
    )
    effective_ai_prompt = (
        args.ai_prompt if args.ai_prompt is not None else cfg.get("ai_prompt", "")
    )
    effective_ai_key = args.ai_key if args.ai_key is not None else ""

    # -- Solver startup message ------------------------------------------------
    available = detect_local_solvers()
    config_source = str(config_path) if config_exists else "defaults"
    if not args.quiet:
        solvers_str = ", ".join(available) if available else "none"
        print(
            f"Solver: {effective_solver} "
            f"(from {config_source})  "
            f"[available: {solvers_str}]"
        )

    # -- Resolve LP file -------------------------------------------------------
    if args.last:
        lp_path = _find_latest_error_lp()
        if lp_path is None:
            if args.quiet:
                print(
                    _c(
                        _YELLOW,
                        "Warning: --last specified but no error*.lp file "
                        "found (quiet mode).",
                    ),
                    file=sys.stderr,
                )
                return 0
            print(
                _c(
                    _RED,
                    "Error: --last specified but no error*.lp file found.",
                ),
                file=sys.stderr,
            )
            return 1
        print(f"Auto-selected LP file: {_c(_BOLD, str(lp_path))}")
    elif args.lp_file is not None:
        lp_path = Path(args.lp_file)
    else:
        parser.print_help()
        return 1

    output_file = Path(args.output) if args.output else None

    # -- Benchmark mode --------------------------------------------------------
    if args.benchmark:
        print(f"\nBenchmarking: {_c(_BOLD, str(lp_path))}")
        report = run_benchmark(
            lp_path,
            timeout=effective_timeout,
        )
        table = format_benchmark_table(report, use_color=_USE_COLOR)
        print(table)
        if output_file:
            _write_report(output_file, [table])
        return 0

    return check_lp(
        lp_path,
        analyze_only=args.analyze_only,
        solver=effective_solver,
        algo=args.algo or "",
        optimal_eps=args.optimal_eps or 0.0,
        feasible_eps=args.feasible_eps or 0.0,
        barrier_eps=args.barrier_eps or 0.0,
        email=effective_email,
        neos_url=effective_neos_url,
        timeout=effective_timeout,
        output_file=output_file,
        quiet=args.quiet,
        no_neos=args.no_neos,
        full=args.full,
        ai=AiOptions(
            enabled=effective_ai_enabled,
            provider=effective_ai_provider,
            model=effective_ai_model,
            prompt=effective_ai_prompt,
            key=effective_ai_key,
        ),
    )


if __name__ == "__main__":
    sys.exit(main())
