# -*- coding: utf-8 -*-
"""Excel writer for converting PLP planning data to igtopt-compatible Excel workbook.

Produces a .xlsx workbook that can be converted back to gtopt JSON + Parquet
by running:  ``igtopt <workbook>.xlsx``

The workbook contains:
- ``.introduction`` sheet – human-readable description of the workbook
- ``.plpinfo`` sheet – PLP conversion statistics (element counts, dates, options)
- ``options`` sheet – gtopt solver / I/O options (key | value pairs)
- One data sheet per array in ``simulation`` and ``system``
- ``CamelCase@fieldname`` time-series sheets from Parquet files in the output dir
"""

from __future__ import annotations

import datetime
import logging
import re
from pathlib import Path
from typing import Any

import pandas as pd

_logger = logging.getLogger(__name__)


def _camel_to_snake_array(cname: str) -> str:
    """Convert a CamelCase element type name to its snake_case_array sheet name.

    Examples
    --------
    >>> _camel_to_snake_array("Demand")
    'demand_array'
    >>> _camel_to_snake_array("GeneratorProfile")
    'generator_profile_array'
    """
    snake = re.sub(r"([A-Z])", lambda m: "_" + m.group(1).lower(), cname)
    return snake.lstrip("_") + "_array"


def _build_uid_to_name_maps(planning: dict[str, Any]) -> dict[str, dict[str, str]]:
    """Build ``uid:N`` → element-name maps for all arrays in the planning dict.

    For each array (in both ``simulation`` and ``system`` sections), build a
    mapping from ``uid:N`` column keys to the human-readable element name.
    This is used when writing time-series ``@``-sheets to the Excel workbook,
    so that output columns use the element name (e.g. ``"LAJA"``) instead of
    the opaque ``uid:N`` key.

    Only arrays where every element has unique names are included; if any two
    elements share a name the whole type is silently omitted to avoid
    ambiguity.

    Args:
        planning: The planning dict returned by ``GTOptWriter.to_json()``.

    Returns:
        Dict mapping CamelCase type names to ``{uid_col: element_name}`` maps.
        E.g. ``{"Demand": {"uid:1": "LAJA", "uid:2": "ANTUCO"}, ...}``.
    """
    result: dict[str, dict[str, str]] = {}
    for section in ("simulation", "system"):
        for array_name, records in planning.get(section, {}).items():
            if not isinstance(records, list) or not records:
                continue
            # Derive CamelCase type name from snake_case array name
            if array_name.endswith("_array"):
                base = array_name[:-6]
            else:
                continue
            cname = re.sub(r"_([a-z])", lambda m: m.group(1).upper(), base)
            cname = cname[0].upper() + cname[1:] if cname else cname

            uid_to_name: dict[str, str] = {}
            seen_names: set[str] = set()
            ok = True
            for rec in records:
                uid = rec.get("uid")
                name = rec.get("name")
                if uid is None or name is None:
                    ok = False
                    break
                name_str = str(name)
                if name_str in seen_names:
                    # Duplicate name – skip this type entirely
                    ok = False
                    break
                seen_names.add(name_str)
                uid_to_name[f"uid:{uid}"] = name_str
            if ok and uid_to_name:
                result[cname] = uid_to_name
    return result


# Ordered sheet list for simulation arrays
_SIM_SHEETS = [
    "block_array",
    "stage_array",
    "scenario_array",
    "phase_array",
    "scene_array",
]

# Ordered sheet list for system arrays
_SYS_SHEETS = [
    "bus_array",
    "generator_array",
    "generator_profile_array",
    "demand_array",
    "demand_profile_array",
    "line_array",
    "battery_array",
    "converter_array",
    "reserve_zone_array",
    "reserve_provision_array",
    "junction_array",
    "waterway_array",
    "flow_array",
    "reservoir_array",
    "turbine_array",
]

# .introduction content (title, heading, body, table entries)
_INTRO_LINES: list[tuple] = [
    ("gtopt Planning Workbook (from plp2gtopt)", "TITLE"),
    ("", ""),
    (
        "This workbook was generated by plp2gtopt from a PLP (PLPMAX/PLPOPT) input case.",
        "BODY",
    ),
    (
        "It can be converted to gtopt JSON + Parquet input files by running:",
        "BODY",
    ),
    ("    igtopt <this_file>.xlsx", "BODY"),
    ("", ""),
    ("Sheet Guide", "HEADING"),
    ("", ""),
    ("Sheet name", "Section", "Description", "TABLE_HEADER"),
    (".introduction", "", "This overview sheet (skipped by igtopt)", "TABLE"),
    (
        ".plpinfo",
        "",
        "PLP conversion statistics and metadata (skipped by igtopt)",
        "TABLE",
    ),
    ("options", "", "gtopt solver and I/O options (one row per option key)", "TABLE"),
    ("block_array", "Simulation", "Operating time blocks", "TABLE"),
    ("stage_array", "Simulation", "Planning stages (groups of blocks)", "TABLE"),
    ("scenario_array", "Simulation", "Probability-weighted scenarios", "TABLE"),
    ("phase_array", "Simulation", "SDDP phases (groups of stages)", "TABLE"),
    ("scene_array", "Simulation", "SDDP scenes (groups of scenarios)", "TABLE"),
    ("bus_array", "System", "Electrical buses (nodes)", "TABLE"),
    ("generator_array", "System", "Generators (thermal, hydro, renewable)", "TABLE"),
    ("generator_profile_array", "System", "Capacity-factor profiles", "TABLE"),
    ("demand_array", "System", "Electricity consumers (loads)", "TABLE"),
    ("demand_profile_array", "System", "Load-shape profiles", "TABLE"),
    ("line_array", "System", "Transmission lines", "TABLE"),
    ("battery_array", "System", "Energy storage devices", "TABLE"),
    ("converter_array", "System", "Battery charge/discharge converters", "TABLE"),
    ("reserve_zone_array", "System", "Spinning-reserve zones", "TABLE"),
    ("reserve_provision_array", "System", "Generator reserve contributions", "TABLE"),
    ("junction_array", "System", "Hydraulic junctions", "TABLE"),
    ("waterway_array", "System", "Water channels between junctions", "TABLE"),
    ("flow_array", "System", "Exogenous water inflows/outflows", "TABLE"),
    ("reservoir_array", "System", "Water reservoirs (lakes, dams)", "TABLE"),
    ("turbine_array", "System", "Hydro turbines", "TABLE"),
    ("", ""),
    ("Time-series Sheets (@-sheets)", "HEADING"),
    ("", ""),
    (
        "Sheets named Element@fieldname (e.g. 'Demand@lmax') contain time-series data.",
        "BODY",
    ),
    (
        "igtopt writes them as Parquet/CSV files to the input directory.",
        "BODY",
    ),
    (
        "Column format: stage, block [, scenario] followed by one uid:N column per element.",
        "BODY",
    ),
    ("", ""),
    ("Generated by plp2gtopt --excel-output", "FOOTER"),
]


def _collect_field_order(sheet_name: str) -> list[str]:
    """Return the preferred column order for a given sheet, from FIELD_META.

    Falls back to an empty list (caller should derive order from the data).
    """
    try:
        from igtopt.template_builder import FIELD_META  # pylint: disable=import-outside-toplevel

        return [f for f, *_ in FIELD_META.get(sheet_name, [])]
    except ImportError:
        return []


def _records_to_df(records: list[dict], sheet_name: str) -> pd.DataFrame:
    """Convert a list of JSON records to a DataFrame with canonical column order."""
    if not records:
        return pd.DataFrame()

    preferred = _collect_field_order(sheet_name)
    all_keys: list[str] = []
    seen: set[str] = set()
    # First add preferred keys that appear in any record
    for key in preferred:
        if key not in seen:
            all_keys.append(key)
            seen.add(key)
    # Then add any remaining keys from the records
    for rec in records:
        for key in rec:
            if key not in seen:
                all_keys.append(key)
                seen.add(key)

    rows: list[dict] = []
    for rec in records:
        row: dict = {}
        for key in all_keys:
            val = rec.get(key)
            if val is None:
                continue
            # Serialize complex values (lists, dicts) as JSON strings
            if isinstance(val, (list, dict)):
                import json

                val = json.dumps(val, separators=(",", ":"))
            row[key] = val
        rows.append(row)

    return pd.DataFrame(rows, columns=all_keys)


def _flatten_options(planning_options: dict) -> list[tuple[str, Any]]:
    """Flatten the planning options dict to (key, value) pairs for the options sheet.

    Nested dicts (like ``sddp_options``) are flattened with their sub-keys.
    Deeply nested dicts (e.g. ``cascade_options.levels[i].model_options``)
    are JSON-stringified so Excel can render them in one cell.
    """
    import json as _json  # noqa: PLC0415

    pairs: list[tuple[str, Any]] = []
    for key, val in planning_options.items():
        if isinstance(val, dict):
            for sub_key, sub_val in val.items():
                if sub_val is None:
                    continue
                if isinstance(sub_val, (dict, list)):
                    pairs.append((sub_key, _json.dumps(sub_val)))
                else:
                    pairs.append((sub_key, sub_val))
        elif isinstance(val, list):
            pairs.append((key, _json.dumps(val)))
        elif val is not None:
            pairs.append((key, val))
    return pairs


def _add_intro_sheet(ws: Any, styles: dict) -> None:
    """Write the .introduction sheet content."""
    ws.column_dimensions["A"].width = 30
    ws.column_dimensions["B"].width = 14
    ws.column_dimensions["C"].width = 58

    row = 1
    for entry in _INTRO_LINES:
        kind = entry[-1]
        if kind == "TITLE":
            cell = ws.cell(row=row, column=1, value=entry[0])
            cell.font = styles["TITLE"]
            ws.merge_cells(f"A{row}:C{row}")
        elif kind == "HEADING":
            cell = ws.cell(row=row, column=1, value=entry[0])
            cell.font = styles["HEADING"]
            ws.merge_cells(f"A{row}:C{row}")
        elif kind == "BODY":
            cell = ws.cell(row=row, column=1, value=entry[0])
            cell.font = styles["BODY"]
            ws.merge_cells(f"A{row}:C{row}")
        elif kind == "FOOTER":
            cell = ws.cell(row=row, column=1, value=entry[0])
            cell.font = styles["FOOTER"]
            ws.merge_cells(f"A{row}:C{row}")
        elif kind == "TABLE_HEADER":
            for col_idx, val in enumerate(entry[:3], start=1):
                c = ws.cell(row=row, column=col_idx, value=val)
                c.font = styles["TABLE_HEADER_FONT"]
                c.fill = styles["TABLE_HEADER_FILL"]
        elif kind == "TABLE":
            for col_idx, val in enumerate(entry[:3], start=1):
                c = ws.cell(row=row, column=col_idx, value=val)
                c.font = styles["BODY"]
                if row % 2 == 0:
                    c.fill = styles["ALT_ROW"]
        row += 1


def _add_plpinfo_sheet(ws: Any, planning: dict, options: dict, styles: dict) -> None:
    """Write the .plpinfo conversion stats sheet."""
    ws.column_dimensions["A"].width = 32
    ws.column_dimensions["B"].width = 22
    ws.column_dimensions["C"].width = 46

    sys = planning.get("system", {})
    sim = planning.get("simulation", {})

    now_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    input_dir = str(options.get("input_dir", ""))
    output_dir = str(options.get("output_dir", ""))
    mo = options.get("model_options", {})

    sections: list[tuple] = [
        ("Conversion Metadata", "HEADING"),
        ("key", "value", "", "TABLE_HEADER"),
        ("input_dir", input_dir, "", "TABLE"),
        ("output_dir", output_dir, "", "TABLE"),
        ("conversion_date", now_str, "", "TABLE"),
        ("", "", "", ""),
        ("System Elements", "HEADING"),
        ("element", "count", "", "TABLE_HEADER"),
        ("buses", len(sys.get("bus_array", [])), "", "TABLE"),
        ("generators", len(sys.get("generator_array", [])), "", "TABLE"),
        (
            "generator_profiles",
            len(sys.get("generator_profile_array", [])),
            "",
            "TABLE",
        ),
        ("demands", len(sys.get("demand_array", [])), "", "TABLE"),
        ("demand_profiles", len(sys.get("demand_profile_array", [])), "", "TABLE"),
        ("lines", len(sys.get("line_array", [])), "", "TABLE"),
        ("batteries", len(sys.get("battery_array", [])), "", "TABLE"),
        ("converters", len(sys.get("converter_array", [])), "", "TABLE"),
        ("reserve_zones", len(sys.get("reserve_zone_array", [])), "", "TABLE"),
        (
            "reserve_provisions",
            len(sys.get("reserve_provision_array", [])),
            "",
            "TABLE",
        ),
        ("junctions", len(sys.get("junction_array", [])), "", "TABLE"),
        ("waterways", len(sys.get("waterway_array", [])), "", "TABLE"),
        ("flows", len(sys.get("flow_array", [])), "", "TABLE"),
        ("reservoirs", len(sys.get("reservoir_array", [])), "", "TABLE"),
        (
            "seepages",
            sum(len(r.get("seepage", [])) for r in sys.get("reservoir_array", [])),
            "",
            "TABLE",
        ),
        ("turbines", len(sys.get("turbine_array", [])), "", "TABLE"),
        (
            "reservoir_efficiencies",
            sum(
                len(r.get("production_factor", []))
                for r in sys.get("reservoir_array", [])
            ),
            "",
            "TABLE",
        ),
        ("", "", "", ""),
        ("Simulation", "HEADING"),
        ("parameter", "value", "", "TABLE_HEADER"),
        ("blocks", len(sim.get("block_array", [])), "", "TABLE"),
        ("stages", len(sim.get("stage_array", [])), "", "TABLE"),
        ("scenarios", len(sim.get("scenario_array", [])), "", "TABLE"),
        ("phases", len(sim.get("phase_array", [])), "", "TABLE"),
        ("scenes", len(sim.get("scene_array", [])), "", "TABLE"),
        ("", "", "", ""),
        ("Key Options", "HEADING"),
        ("option", "value", "", "TABLE_HEADER"),
        ("input_dir", input_dir, "", "TABLE"),
        ("method", str(options.get("method", "sddp")), "", "TABLE"),
        ("hydrologies", str(options.get("hydrologies", "1")), "", "TABLE"),
        ("discount_rate", str(options.get("discount_rate", 0.0)), "", "TABLE"),
        ("use_single_bus", str(mo.get("use_single_bus", False)), "", "TABLE"),
        ("use_kirchhoff", str(mo.get("use_kirchhoff", False)), "", "TABLE"),
        ("demand_fail_cost", str(mo.get("demand_fail_cost", 1000)), "", "TABLE"),
        (
            "scale_objective",
            str(mo.get("scale_objective", 1_000)),
            "",
            "TABLE",
        ),
    ]

    for row_idx, entry in enumerate(sections, start=1):
        kind = entry[-1]
        if kind == "HEADING":
            cell = ws.cell(row=row_idx, column=1, value=entry[0])
            cell.font = styles["HEADING"]
        elif kind == "TABLE_HEADER":
            for col_idx, val in enumerate(entry[:2], start=1):
                c = ws.cell(row=row_idx, column=col_idx, value=val)
                c.font = styles["TABLE_HEADER_FONT"]
                c.fill = styles["TABLE_HEADER_FILL"]
        elif kind == "TABLE":
            ws.cell(row=row_idx, column=1, value=entry[0]).font = styles["BODY"]
            ws.cell(row=row_idx, column=2, value=entry[1]).font = styles["BODY"]
            if row_idx % 2 == 0:
                ws.cell(row=row_idx, column=1).fill = styles["ALT_ROW"]
                ws.cell(row=row_idx, column=2).fill = styles["ALT_ROW"]


def _add_options_sheet(ws: Any, planning_options: dict, styles: dict) -> None:
    """Write the options sheet with key|value|description columns."""
    ws.column_dimensions["A"].width = 34
    ws.column_dimensions["B"].width = 22
    ws.column_dimensions["C"].width = 50

    # Header row
    for col_idx, header in enumerate(["option", "value", "description"], start=1):
        c = ws.cell(row=1, column=col_idx, value=header)
        c.font = styles["HEADER_FONT"]
        c.fill = styles["HEADER_FILL"]

    pairs = _flatten_options(planning_options)
    for row_idx, (key, val) in enumerate(pairs, start=2):
        ws.cell(row=row_idx, column=1, value=key)
        ws.cell(row=row_idx, column=2, value=val)

    ws.freeze_panes = "A2"


def _add_data_sheet(
    ws: Any,
    sheet_name: str,
    records: list[dict],
    styles: dict,
    get_column_letter: Any,
) -> None:
    """Write a data sheet from a list of JSON records (no help rows)."""
    df = _records_to_df(records, sheet_name)
    if df.empty:
        return

    cols = list(df.columns)

    # Row 1: header
    for col_idx, col_name in enumerate(cols, start=1):
        c = ws.cell(row=1, column=col_idx, value=col_name)
        c.font = styles["HEADER_FONT"]
        c.fill = styles["HEADER_FILL"]

    # Row 2+: data
    for row_idx, row in enumerate(df.itertuples(index=False), start=2):
        for col_idx, val in enumerate(row, start=1):
            if val is None or (isinstance(val, float) and pd.isna(val)):
                continue
            ws.cell(row=row_idx, column=col_idx, value=val)

    # Column widths
    for col_idx, col_name in enumerate(cols, start=1):
        col_letter = get_column_letter(col_idx)
        ws.column_dimensions[col_letter].width = max(12, len(str(col_name)) + 4)

    ws.freeze_panes = "A2"


def _add_timeseries_sheet(
    ws: Any,
    sheet_name: str,
    df: pd.DataFrame,
    styles: dict,
    get_column_letter: Any,
) -> None:
    """Write a time-series @-sheet from a DataFrame."""
    if df.empty:
        return

    cols = list(df.columns)

    # Row 1: header
    for col_idx, col_name in enumerate(cols, start=1):
        c = ws.cell(row=1, column=col_idx, value=col_name)
        c.font = styles["HEADER_FONT"]
        c.fill = styles["HEADER_FILL"]

    # Row 2+: data (use itertuples for performance)
    for row_idx, row in enumerate(df.itertuples(index=False), start=2):
        for col_idx, val in enumerate(row, start=1):
            if val is None:
                continue
            # Handle numpy scalars
            try:
                import numpy as np

                if isinstance(val, (np.integer,)):
                    val = int(val)
                elif isinstance(val, (np.floating,)):
                    val = float(val)
                    if pd.isna(val):
                        continue
            except ImportError:
                pass
            ws.cell(row=row_idx, column=col_idx, value=val)

    # Column widths
    for col_idx, col_name in enumerate(cols, start=1):
        col_letter = get_column_letter(col_idx)
        ws.column_dimensions[col_letter].width = max(10, len(str(col_name)) + 3)

    ws.freeze_panes = "A2"


def build_plp_excel(
    planning: dict[str, Any],
    output_dir: Path,
    output_path: Path,
    options: dict[str, Any],
) -> None:
    """Build an igtopt-compatible Excel workbook from PLP planning data.

    The workbook contains:
    - ``.introduction`` sheet – overview and sheet guide
    - ``.plpinfo`` sheet – conversion statistics and metadata
    - ``options`` sheet – flattened planning options (key|value)
    - One sheet per non-empty array in simulation/system
    - Time-series ``CamelCase@fieldname`` sheets from Parquet files in output_dir

    Args:
        planning: Planning dict returned by ``GTOptWriter.to_json()``.
        output_dir: Directory containing Parquet/CSV time-series files.
        output_path: Destination ``.xlsx`` file path.
        options: Original plp2gtopt conversion options (for ``.plpinfo``).
    """
    try:
        import openpyxl
        from openpyxl.styles import Alignment, Font, PatternFill
        from openpyxl.utils import get_column_letter
    except ImportError as exc:
        raise ImportError(
            f"openpyxl is required for Excel output. "
            f"Install with: pip install openpyxl\n{exc}"
        ) from exc

    # -- Style definitions (consistent with igtopt template_builder) ----------
    styles: dict[str, Any] = {
        "TITLE": Font(name="Calibri", size=16, bold=True, color="1F3864"),
        "HEADING": Font(name="Calibri", size=12, bold=True, color="2F5496"),
        "BODY": Font(name="Calibri", size=10),
        "FOOTER": Font(name="Calibri", size=9, italic=True, color="808080"),
        "HEADER_FILL": PatternFill("solid", fgColor="1F3864"),
        "ALT_ROW": PatternFill("solid", fgColor="DCE6F1"),
        "TABLE_HEADER_FILL": PatternFill("solid", fgColor="4472C4"),
        "HEADER_FONT": Font(name="Calibri", bold=True, color="FFFFFF"),
        "TABLE_HEADER_FONT": Font(name="Calibri", bold=True, color="FFFFFF"),
        "ALIGN_LEFT": Alignment(horizontal="left"),
    }

    wb = openpyxl.Workbook()

    # 1. .introduction sheet (created as the default sheet)
    ws_intro = wb.active
    ws_intro.title = ".introduction"
    _add_intro_sheet(ws_intro, styles)

    # 2. .plpinfo sheet
    ws_info = wb.create_sheet(".plpinfo")
    _add_plpinfo_sheet(ws_info, planning, options, styles)

    # 3. options sheet
    ws_opts = wb.create_sheet("options")
    _add_options_sheet(ws_opts, planning.get("options", {}), styles)

    # 4. Simulation array sheets
    sim = planning.get("simulation", {})
    for sheet_name in _SIM_SHEETS:
        records = sim.get(sheet_name)
        if not records:
            continue
        ws = wb.create_sheet(sheet_name)
        _add_data_sheet(ws, sheet_name, records, styles, get_column_letter)

    # 5. System array sheets (skip non-array metadata like "name", "version")
    sys_data = planning.get("system", {})
    for sheet_name in _SYS_SHEETS:
        records = sys_data.get(sheet_name)
        if not records:
            continue
        ws = wb.create_sheet(sheet_name)
        _add_data_sheet(ws, sheet_name, records, styles, get_column_letter)

    # 6. Time-series @-sheets from Parquet files in output_dir.
    # Build uid→name maps from the planning dict so column names can be
    # written as human-readable element names (e.g. "LAJA") instead of
    # opaque "uid:N" keys.  igtopt resolves them back to uid:N when reading.
    uid_to_name_maps = _build_uid_to_name_maps(planning)

    if output_dir.exists():
        ts_count = 0
        for parquet_file in sorted(output_dir.rglob("*.parquet")):
            rel = parquet_file.relative_to(output_dir)
            parts = rel.parts
            # Expected: <CamelCaseDir>/<fieldname>.parquet
            if len(parts) != 2:
                _logger.debug("Skipping nested parquet: %s", parquet_file)
                continue
            cname = parts[0]
            fname = parquet_file.stem
            at_sheet_name = f"{cname}@{fname}"
            try:
                df = pd.read_parquet(parquet_file)
                if df.empty:
                    continue
                # Rename uid:N columns to element names if mapping available
                uid_to_name = uid_to_name_maps.get(cname, {})
                if uid_to_name:
                    df = df.rename(columns=uid_to_name)
                ws = wb.create_sheet(at_sheet_name)
                _add_timeseries_sheet(ws, at_sheet_name, df, styles, get_column_letter)
                ts_count += 1
                _logger.debug("Added @-sheet: %s (%d rows)", at_sheet_name, len(df))
            except Exception as exc:  # noqa: BLE001  # pylint: disable=broad-exception-caught
                # Intentionally broad: Parquet/Arrow/openpyxl can raise many
                # unrelated exception types (ArrowInvalid, OSError, ValueError,
                # UnsupportedOperation, etc.) and we must not crash the entire
                # Excel export just because one @-sheet's data is unreadable.
                _logger.warning("Could not read parquet file %s: %s", parquet_file, exc)

        _logger.info("Added %d time-series @-sheets from %s", ts_count, output_dir)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(output_path)
    _logger.info("Excel workbook written: %s", output_path)
