"""Schema-portability + XML-only integration tests.

These exercise the MasterDataSet reader against PLEXOS XML databases
generated by an independent toolchain (NREL plexos-coad,
BSD-3-Clause). The fixtures live under ``tests/data/plexos_coad/``
as LZMA-compressed XML, so the test starts by decompressing into a
``tmp_path``.

P3.5 added ``t_data`` fallbacks (Pmax/Pmin/Load/HeatRate/Reactance)
so the ``118-Bus.xml`` benchmark — which has no companion CSVs —
solves end-to-end through ``gtopt --lp-only``. RTS-96 is partially
supported: it uses ``Load Participation Factor`` for demand, which
requires denormalising against a system-level Load that v0 doesn't
synthesise yet.
"""

from __future__ import annotations

import json
import lzma
import os
import shutil
import subprocess
from pathlib import Path

import pytest

from plexos2gtopt.plexos2gtopt import convert_plexos_bundle
from plexos2gtopt.plexos_xml import load_xml


_FIXTURES = Path(__file__).resolve().parent / "data" / "plexos_coad"


def _decompress(name: str, target_dir: Path) -> Path:
    """Decompress ``<name>.xml.xz`` from the fixtures dir into ``target_dir``."""
    src = _FIXTURES / f"{name}.xml.xz"
    if not src.is_file():
        pytest.skip(f"fixture not vendored: {src}")
    dst = target_dir / f"{name}.xml"
    with lzma.open(src, "rb") as compressed, dst.open("wb") as out:
        shutil.copyfileobj(compressed, out)
    return dst


def test_load_118_bus_topology(tmp_path: Path) -> None:
    """The plexos-coad 118-bus benchmark loads with the expected counts."""
    xml = _decompress("118-Bus", tmp_path)
    db = load_xml(xml)
    # The plexos-coad cases use older PLEXOS schemas with class IDs that
    # differ from the CEN PCP bundle, so the reader must look up classes
    # by *name* (Generator, Node, Line) rather than hard-coded IDs.
    assert db.class_id("Node") is not None
    assert db.class_id("Generator") is not None
    assert db.class_id("Line") is not None
    assert len(db.objects_of_class("Node")) == 118
    assert len(db.objects_of_class("Generator")) == 54
    assert len(db.objects_of_class("Line")) == 186


def test_load_rts96_topology(tmp_path: Path) -> None:
    """The plexos-coad RTS-96 benchmark exposes the standard 3-area split."""
    xml = _decompress("RTS-96", tmp_path)
    db = load_xml(xml)
    assert len(db.objects_of_class("Node")) == 73
    assert len(db.objects_of_class("Generator")) == 99
    assert len(db.objects_of_class("Line")) == 120
    # RTS-96 ships an explicit Fuel catalogue; 118-Bus doesn't.
    assert len(db.objects_of_class("Fuel")) == 5


def test_t_data_indexes_build_lazily(tmp_path: Path) -> None:
    """Static-property lookup works against an external schema too.

    Without committing to specific property IDs (which vary across
    PLEXOS releases), just confirm that ``data_for`` and
    ``static_property`` don't crash and return sane fallbacks for
    objects that exist in the fixture.
    """
    xml = _decompress("RTS-96", tmp_path)
    db = load_xml(xml)
    nodes = db.objects_of_class("Node")
    assert nodes, "RTS-96 must contain at least one Node"
    # Asking for a property that the System-Node collection doesn't
    # carry should hit the default-fallback branch cleanly.
    bogus = db.static_property("Node", nodes[0].object_id, "DoesNotExist", default=-1.0)
    assert bogus == -1.0


def _gtopt_binary() -> Path | None:
    """Return a usable ``gtopt`` executable path or ``None``."""
    env = os.environ.get("GTOPT_BIN")
    if env and Path(env).is_file() and os.access(env, os.X_OK):
        return Path(env)
    repo_root = Path(__file__).resolve().parents[3]
    candidate = repo_root / "build" / "standalone" / "gtopt"
    if candidate.is_file() and os.access(candidate, os.X_OK):
        return candidate
    on_path = shutil.which("gtopt")
    return Path(on_path) if on_path else None


_skip_if_no_gtopt = pytest.mark.skipif(
    _gtopt_binary() is None,
    reason="gtopt binary not available (set GTOPT_BIN or build standalone)",
)


def test_118_bus_full_convert(tmp_path: Path) -> None:
    """P3.5: convert 118-Bus.xml end-to-end via t_data-only fallback.

    The plexos-coad 118-bus benchmark ships the entire catalogue inside
    the XML database (no companion CSV time-series), so this round-trip
    exercises every t_data fallback we added: Pmax via Max Capacity,
    Load via Node→Load, ratings via Max Flow / Min Flow, gcost via
    Heat Rate Incr × Fuel Price.
    """
    # The bundle locator looks for a file literally named
    # ``DBSEN_PRGDIARIO.xml``, so we decompress under that name.
    bundle_dir = tmp_path / "bundle"
    bundle_dir.mkdir()
    xml_dst = bundle_dir / "DBSEN_PRGDIARIO.xml"
    xml_src = _FIXTURES / "118-Bus.xml.xz"
    with lzma.open(xml_src, "rb") as fin, xml_dst.open("wb") as fout:
        shutil.copyfileobj(fin, fout)

    out_dir = tmp_path / "out"
    out_file = out_dir / "118-bus.json"
    convert_plexos_bundle(
        {
            "input_bundle": bundle_dir,
            "output_dir": out_dir,
            "output_file": out_file,
            # Synthetic IEEE 118-bus has no CEN PCP solution .accdb;
            # use uniform-hourly explicitly.
            "horizon_mode": "hourly",
            "horizon_days": 1,
        }
    )
    planning = json.loads(out_file.read_text())
    system = planning["system"]
    assert len(system["bus_array"]) == 118
    # 118-Bus ships the native PLEXOS ``Voltage`` node property on
    # every bus (106×138 kV, 11×345 kV, 1×161 kV) — the names are pure
    # bus numbers, so only the property path can populate ``voltage``.
    assert {b["voltage"] for b in system["bus_array"]} == {138.0, 345.0, 161.0}
    assert len(system["generator_array"]) == 54
    assert len(system["line_array"]) == 186
    assert len(system["demand_array"]) >= 50, (
        "expected ≥50 buses with non-zero Load on 118-bus"
    )
    # Every generator carries a populated pmax (from Max Capacity).
    # The benchmark mixes plant sizes: 100 / 130 / 260 / 707 MW etc.
    assert all(g["pmax"] > 0 for g in system["generator_array"])
    # Every generator carries piecewise heat-rate slopes — the LP
    # cost = fuel.price × heat_rate_segments[k]. (Prior to the
    # piecewise wiring the cost lived in scalar ``gcost`` instead.)
    assert all(
        any(s > 0 for s in g.get("heat_rate_segments", []))
        for g in system["generator_array"]
    )
    # Reactance is populated for every line (DC OPF gate).
    assert all(line.get("reactance", 0) > 0 for line in system["line_array"])


@_skip_if_no_gtopt
def test_118_bus_solves_with_gtopt(tmp_path: Path) -> None:
    """`gtopt --lp-only` accepts the 118-Bus planning."""
    bundle_dir = tmp_path / "bundle"
    bundle_dir.mkdir()
    xml_dst = bundle_dir / "DBSEN_PRGDIARIO.xml"
    xml_src = _FIXTURES / "118-Bus.xml.xz"
    with lzma.open(xml_src, "rb") as fin, xml_dst.open("wb") as fout:
        shutil.copyfileobj(fin, fout)

    out_dir = tmp_path / "out"
    out_file = out_dir / "118-bus.json"
    convert_plexos_bundle(
        {
            "input_bundle": bundle_dir,
            "output_dir": out_dir,
            "output_file": out_file,
            # Synthetic IEEE 118-bus has no CEN PCP solution .accdb;
            # use uniform-hourly explicitly.
            "horizon_mode": "hourly",
            "horizon_days": 1,
        }
    )
    gtopt = _gtopt_binary()
    assert gtopt is not None
    proc = subprocess.run(
        [str(gtopt), "--lp-only", "-s", out_file.name],
        cwd=out_dir,
        capture_output=True,
        timeout=60,
        check=False,
    )
    assert proc.returncode == 0, (
        f"gtopt --lp-only (118-Bus) failed: {proc.stderr.decode()[:500]}"
    )
