# SPDX-License-Identifier: BSD-3-Clause
"""gtopt_compress_lp – compress LP files generated by gtopt.

This script compresses LP debug files (``*.lp``) produced by gtopt using a
user-configured compressor.  It mirrors the ``gtopt_check_lp`` design: a
config file (``~/.gtopt_compress_lp.conf``) stores the preferred tool, and an
interactive first-run wizard helps users install and configure one.

Public API
----------
:func:`compress_lp`   — compress a single LP file, return the output path.
:func:`main`          — CLI entry point registered as ``gtopt_compress_lp``.

Sub-modules
-----------
:mod:`._colors`  — ANSI colour helpers (shared pattern with gtopt_check_lp)
:mod:`._config`  — Config file I/O and interactive setup wizard
"""

from ._config import (
    default_config_path,
    load_config,
    run_interactive_setup,
    save_config,
)
from .gtopt_compress_lp import compress_lp, main  # noqa: F401

__all__ = [
    "compress_lp",
    "default_config_path",
    "load_config",
    "main",
    "run_interactive_setup",
    "save_config",
]
