#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
"""
gtopt_compress_lp — Compress LP files generated by gtopt.

When gtopt saves LP debug files (``*.lp``) via ``lp_debug=true`` or
``just_build_lp=true``, this tool compresses them using a user-configured
external compressor, freeing disk space without losing diagnostic value.

Configuration
-------------
User preferences are stored in ``~/.gtopt_compress_lp.conf`` (INI format).
On the first run (without ``--quiet``) the tool prompts interactively and
recommends available compression tools.

Run ``gtopt_compress_lp --init-config`` at any time to create or update the
configuration file.

Quiet mode (``--quiet``)
------------------------
In quiet mode the tool:

* **Never fails** — always exits with code 0.
* **Never prompts** — skips the interactive first-run setup wizard even when
  no config file is present; prints a warning to stderr instead.
* **Tries its best** — attempts the configured compressor, then falls back
  to the next available tool, then continues without compressing.
* **Does not stall** — all subprocess calls use timeouts.

Quiet mode is used by the ``gtopt`` binary (via ``LpDebugWriter``) to
compress LP files as a fire-and-forget background task.

Compression cascade (same order as the C++ ``LpDebugWriter``):
  1. Configured compressor (from config file, default ``auto``).
  2. First available compressor found on PATH.
  3. Skip compression and leave the original ``.lp`` file unchanged.

Usage
-----
::

    gtopt_compress_lp file.lp
    gtopt_compress_lp file.lp --quiet          # non-failing, used by gtopt
    gtopt_compress_lp file.lp --codec zstd     # suggest a codec to use
    gtopt_compress_lp file.lp --compressor zstd
    gtopt_compress_lp --init-config            # create/update config file
    gtopt_compress_lp --list-tools             # show available tools + status
"""

from __future__ import annotations

import argparse
import shlex
import subprocess
import sys
from pathlib import Path
from typing import Optional

from . import _colors as col
from ._config import (
    default_config_path,
    load_config,
    pick_auto_compressor,
    print_compressor_status,
    run_interactive_setup,
)

__version__ = "0.1.0"

# ---------------------------------------------------------------------------
# Output extension mapping per compressor
# ---------------------------------------------------------------------------

_COMPRESSOR_EXTENSIONS: dict[str, str] = {
    "gzip": ".gz",
    "zstd": ".zst",
    "lz4": ".lz4",
    "bzip2": ".bz2",
    "xz": ".xz",
    "lzma": ".lzma",
}

# Compressor command templates.  ``{file}`` is replaced with the file path.
# Most compressors compress in-place and delete the original by default.
_COMPRESSOR_COMMANDS: dict[str, list[str]] = {
    "gzip": ["gzip", "-f"],
    "zstd": ["zstd", "--rm", "-f"],
    "lz4": ["lz4", "-f", "--rm"],
    "bzip2": ["bzip2", "-f"],
    "xz": ["xz", "-f"],
    "lzma": ["lzma", "-f"],
}

# Default subprocess timeout in seconds (generous; LP files can be large)
_TIMEOUT_S = 120


# ---------------------------------------------------------------------------
# Core compression function
# ---------------------------------------------------------------------------


def _run_compressor(
    binary: str,
    extra_args: list[str],
    lp_path: Path,
    quiet: bool,
) -> Optional[Path]:
    """Run *binary* on *lp_path*.

    Returns the compressed output path on success, or ``None`` on failure.
    Never raises.
    """
    base_args = _COMPRESSOR_COMMANDS.get(binary, [binary, "-f"])
    ext = _COMPRESSOR_EXTENSIONS.get(binary, ".gz")
    out_path = Path(str(lp_path) + ext)
    cmd = base_args + extra_args + [str(lp_path)]
    # lz4 writes to stdout unless an explicit output path is given.
    if binary == "lz4":
        cmd.append(str(out_path))
    try:
        # Use text=False to avoid UnicodeDecodeError when a compressor
        # (e.g. lz4) writes binary data to stdout.
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=False,
            timeout=_TIMEOUT_S,
            check=False,
        )
        if result.returncode == 0:
            if out_path.exists():
                return out_path
            # Some compressors (e.g. lz4 with --rm) keep the original name.
            if not lp_path.exists():
                return out_path  # best guess
            return None
        if not quiet:
            print(
                f"  {binary}: returned exit code {result.returncode}",
                file=sys.stderr,
            )
            if result.stderr:
                stderr_text = result.stderr.decode("utf-8", errors="replace").strip()
                print(f"  {stderr_text}", file=sys.stderr)
        return None
    except FileNotFoundError:
        if not quiet:
            print(f"  '{binary}' not found on PATH", file=sys.stderr)
        return None
    except subprocess.TimeoutExpired:
        if not quiet:
            print(f"  '{binary}' timed out after {_TIMEOUT_S}s", file=sys.stderr)
        return None
    except OSError as exc:
        if not quiet:
            print(f"  '{binary}' error: {exc}", file=sys.stderr)
        return None


def compress_lp(
    lp_path: Path,
    cfg: dict[str, str],
    quiet: bool = False,
    codec_hint: str | None = None,
) -> Optional[Path]:
    """Compress *lp_path* using the configured compressor.

    *codec_hint* is an optional suggestion from the caller (e.g. the gtopt
    binary's ``lp_compression`` option passed as ``--codec``).  When provided
    it is tried first.  If it is unknown or the binary is unavailable a warning
    is printed (in non-quiet mode) and the normal config/auto cascade is used.

    Cascade:
    1. ``codec_hint`` (if provided and available).
    2. Configured compressor (``cfg["compressor"]``; ``"auto"`` → first available).
    3. First available tool found on PATH.
    4. Return ``None`` (leave the original unchanged).

    Returns the compressed file path, or ``None`` when nothing worked.
    """
    if not lp_path.exists():
        if not quiet:
            print(
                f"Warning: file not found: {lp_path}",
                file=sys.stderr,
            )
        return None

    compressor = cfg.get("compressor", "auto").strip()
    extra_args = shlex.split(cfg.get("extra_args", ""))

    candidates: list[str] = []

    # ── codec_hint: validate and insert at the front ─────────────────────
    if codec_hint and codec_hint not in ("none", "auto", ""):
        if codec_hint in _COMPRESSOR_COMMANDS:
            candidates.append(codec_hint)
        else:
            if not quiet:
                print(
                    f"  Warning: unknown codec '{codec_hint}' requested; "
                    "falling back to configured compressor.",
                    file=sys.stderr,
                )
            # Unknown codec — ignore and fall through to config/auto.

    # ── configured compressor ─────────────────────────────────────────────
    if compressor != "auto" and compressor and compressor not in candidates:
        candidates.append(compressor)

    # ── auto-detected fallback chain ──────────────────────────────────────
    auto = pick_auto_compressor()
    if auto and auto not in candidates:
        candidates.append(auto)

    for binary in candidates:
        result = _run_compressor(binary, extra_args, lp_path, quiet)
        if result is not None:
            if not quiet:
                print(f"  compressed {lp_path.name} → {result.name}")
            return result

    if not quiet:
        print(
            f"Warning: no compressor available; keeping {lp_path}",
            file=sys.stderr,
        )
    return None


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="gtopt_compress_lp",
        description=(
            "Compress LP debug files produced by gtopt.\n\n"
            "On the first run (without --quiet) the tool shows available "
            "compression tools and prompts for preferences."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "lp_files",
        metavar="FILE.lp",
        nargs="*",
        help="LP file(s) to compress.",
    )
    parser.add_argument(
        "--init-config",
        action="store_true",
        help="Run the interactive setup wizard and exit.",
    )
    parser.add_argument(
        "--list-tools",
        action="store_true",
        help="Show available compression tools and exit.",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help=(
            "Non-interactive mode: never prompt, never fail.  Used by the gtopt binary."
        ),
    )
    parser.add_argument(
        "--codec",
        default=None,
        metavar="CODEC",
        help=(
            "Codec suggestion from the caller (e.g. 'gzip', 'zstd', 'lz4'). "
            "Tried first; falls back to the configured compressor when the "
            "codec is unknown or unavailable.  Ignored when 'none' or empty."
        ),
    )
    parser.add_argument(
        "--compressor",
        default=None,
        metavar="TOOL",
        help=(
            "Override the configured compressor (e.g. 'gzip', 'zstd', 'lz4'). "
            "Use 'auto' to pick the first available tool."
        ),
    )
    parser.add_argument(
        "--config",
        default=None,
        metavar="PATH",
        help="Path to the config file (default: ~/.gtopt_compress_lp.conf).",
    )
    parser.add_argument(
        "--color",
        default=None,
        choices=["auto", "always", "never"],
        help="Terminal colour output (default: auto).",
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {__version__}",
    )
    return parser


def main(argv: Optional[list[str]] = None) -> int:
    """Entry point for the ``gtopt_compress_lp`` console script.

    Returns an exit code: ``0`` on success (or when ``--quiet`` suppresses
    all errors), non-zero only in non-quiet mode on hard errors.
    """
    parser = _build_parser()
    args = parser.parse_args(argv)

    # ── Colour setup ───────────────────────────────────────────────────────
    color_flag = args.color
    if color_flag is None:
        color_flag = "auto"
    use_color = color_flag == "always" or (color_flag == "auto" and sys.stdout.isatty())
    col.USE_COLOR = use_color

    def _c(code: str, text: str) -> str:
        return f"{code}{text}{col._RESET}" if use_color else text  # noqa: SLF001

    # ── Config path ────────────────────────────────────────────────────────
    config_path = Path(args.config) if args.config else default_config_path()

    # ── --list-tools ───────────────────────────────────────────────────────
    if args.list_tools:
        print_compressor_status(use_color=use_color)
        return 0

    # ── --init-config ──────────────────────────────────────────────────────
    if args.init_config:
        run_interactive_setup(config_path, use_color=use_color)
        return 0

    # ── Load config ────────────────────────────────────────────────────────
    cfg = load_config(config_path)

    # Override config with CLI arg if given
    if args.compressor is not None:
        cfg["compressor"] = args.compressor

    # ── First-run interactive setup (non-quiet only) ───────────────────────
    if not args.quiet and not config_path.exists():
        print(
            _c(
                col._YELLOW,  # noqa: SLF001
                "\nNo configuration file found.",
            )
        )
        if sys.stdin.isatty():
            answer = _prompt_first_run(use_color)
            if answer:
                cfg = run_interactive_setup(config_path, use_color=use_color)
        else:
            print(
                "  Run 'gtopt_compress_lp --init-config' to configure.",
                file=sys.stderr,
            )

    # ── No files → show help ───────────────────────────────────────────────
    if not args.lp_files:
        if not args.quiet:
            parser.print_help()
        return 0

    # ── Compress files ─────────────────────────────────────────────────────
    all_ok = True
    for file_arg in args.lp_files:
        lp_path = Path(file_arg)
        result = compress_lp(lp_path, cfg, quiet=args.quiet, codec_hint=args.codec)
        if result is None and not lp_path.name.endswith(
            (".gz", ".zst", ".lz4", ".bz2", ".xz", ".lzma")
        ):
            # Only count as failure when we expected to compress something
            if lp_path.exists():
                all_ok = False

    return 0 if (args.quiet or all_ok) else 1


def _prompt_first_run(use_color: bool) -> bool:
    """Ask the user whether to run the setup wizard.  Returns True if yes."""

    def _c(code: str, text: str) -> str:
        return f"{code}{text}{col._RESET}" if use_color else text  # noqa: SLF001

    print(
        "\n  "
        + _c(col._BOLD, "gtopt_compress_lp")  # noqa: SLF001
        + " needs to be configured before first use."
    )
    print("  This wizard will show available compression tools and let you pick one.\n")
    try:
        answer = input("  Run setup now? [Y/n]: ").strip().lower()
        return answer in ("", "y", "yes")
    except (EOFError, KeyboardInterrupt):
        return False


if __name__ == "__main__":
    sys.exit(main())
