
FIND_LIBRARY(COIN_OSIGRB_LIBRARY
  NAMES OsiGrb libOsiGrb
  HINTS ${COIN_ROOT_DIR}/lib/coin
  HINTS ${COIN_ROOT_DIR}/lib
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OSIGRB DEFAULT_MSG
  COIN_OSIGRB_LIBRARY
)

