

FIND_LIBRARY(COIN_OSICPX_LIBRARY
  NAMES OsiCpx libOsiCpx
  HINTS ${COIN_ROOT_DIR}/lib/coin
  HINTS ${COIN_ROOT_DIR}/lib
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OSICPX DEFAULT_MSG
  COIN_OSICPX_LIBRARY
)
