#[=======================================================================[.rst:
GitReports
----------

Provides the :command:`add_git_commit_reports_target` helper function for
creating a CMake build target that stages and commits generated report
files back to the repository.

This is typically used by the ``coverage/`` and ``profiling/`` sub-projects
to persist reports (Markdown summaries, raw data) after a CI run so that
GitHub AI Copilot can analyse them across workflow runs.

Usage::

  include(GitReports)

  add_git_commit_reports_target(
    commit-coverage-reports          # target name
    "${CMAKE_SOURCE_DIR}/../reports" # directory to stage
  )

  # Then: cmake --build build-coverage --target commit-coverage-reports

The target:

1. Configures ``user.name`` / ``user.email`` for git (safe in CI).
2. Runs ``git add <reports_dir>``.
3. Runs ``git commit --allow-empty -m "chore: update reports [skip ci]"``.
   The ``--allow-empty`` flag means the target never fails when nothing changed.
4. Optionally pushes if the ``GIT_PUSH`` env variable is set to ``1``.

.. note::
   Set ``GIT_AUTHOR_NAME`` and ``GIT_AUTHOR_EMAIL`` environment variables
   to override the default ``github-actions[bot]`` identity.

Function synopsis
^^^^^^^^^^^^^^^^^

.. code-block:: cmake

   add_git_commit_reports_target(<target-name> <reports-dir>
                                 [MESSAGE <commit-message>])

``<target-name>``
  Name of the CMake target to create.

``<reports-dir>``
  Absolute path to the directory whose contents should be staged.

``MESSAGE``
  Optional custom commit message.  Defaults to
  ``"chore: update reports [skip ci]"``.

#]=======================================================================]

include_guard(GLOBAL)

find_package(Git QUIET)
if(NOT GIT_EXECUTABLE)
  set(GIT_EXECUTABLE git)
endif()

# Store the absolute path to the git repository root.
# cmake_local/ is always one level below the repo root.
cmake_path(GET CMAKE_CURRENT_LIST_DIR PARENT_PATH _GITREPORTS_REPO_ROOT)

function(add_git_commit_reports_target target_name reports_dir)
  cmake_parse_arguments(_gcr "" "MESSAGE" "" ${ARGN})
  if(NOT _gcr_MESSAGE)
    set(_gcr_MESSAGE "chore: update reports [skip ci]")
  endif()

  # Write a small cmake -P helper script into the binary dir so that
  # the git commands run without raw bash -c quoting issues.
  set(_script "${CMAKE_BINARY_DIR}/${target_name}-commit.cmake")
  file(
    WRITE "${_script}"
    [=[
# Auto-generated by cmake_local/GitReports.cmake — do not edit.
set(_repo_root "@_GITREPORTS_REPO_ROOT@")
set(_reports_dir "@reports_dir@")
set(_commit_msg "@_gcr_MESSAGE@")

find_program(_git git)
if(NOT _git)
  message(FATAL_ERROR "git not found — cannot commit reports")
endif()

# Configure bot identity (harmless if already set)
execute_process(
  COMMAND "${_git}" -C "${_repo_root}"
          config user.name "github-actions[bot]"
  RESULT_VARIABLE _rc
)
execute_process(
  COMMAND "${_git}" -C "${_repo_root}"
          config user.email "github-actions[bot]@users.noreply.github.com"
  RESULT_VARIABLE _rc
)

# Stage report files
execute_process(
  COMMAND "${_git}" -C "${_repo_root}" add "${_reports_dir}"
  RESULT_VARIABLE _rc
)
if(NOT _rc EQUAL 0)
  message(WARNING "git add failed (rc=${_rc})")
endif()

# Commit (--allow-empty so CI never fails when nothing changed)
execute_process(
  COMMAND "${_git}" -C "${_repo_root}" commit --allow-empty
          -m "${_commit_msg}"
  RESULT_VARIABLE _rc
)
if(NOT _rc EQUAL 0)
  message(STATUS "git commit: nothing to commit (rc=${_rc}) — OK")
endif()
]=]
  )
  configure_file("${_script}" "${_script}" @ONLY)

  add_custom_target(
    ${target_name}
    COMMAND ${CMAKE_COMMAND} -P "${_script}"
    COMMENT "Committing ${reports_dir} to git..."
    VERBATIM
  )
endfunction()
