# SPDX-License-Identifier: BSD-3-Clause
"""Configuration file I/O for gtopt_check_json."""

import configparser
import shutil
import subprocess
import sys
from pathlib import Path

from . import _colors as col

_CONFIG_SECTION = "gtopt_check_json"

# Each check can be enabled / disabled individually via the config file.
# The key is the check id; the value is "true" or "false".
CHECK_DEFAULTS: dict[str, str] = {
    "uid_uniqueness": "true",
    "name_uniqueness": "true",
    "demand_lmax_nonneg": "true",
    "affluent_nonneg": "true",
    "element_references": "true",
    "bus_connectivity": "true",
    "unreferenced_elements": "true",
    "capacity_adequacy": "true",
    "ai_system_analysis": "false",
}

_CONFIG_DEFAULTS: dict[str, str] = {
    "color": "auto",
    "ai_enabled": "false",
    "ai_provider": "github",
    "ai_model": "",
    "ai_prompt": "",
    **{f"check_{k}": v for k, v in CHECK_DEFAULTS.items()},
}

# Supported AI providers (kept in sync with gtopt_check_lp._ai._AI_PROVIDERS).
_AI_PROVIDERS = ("claude", "openai", "deepseek", "github")
_AI_DEFAULT_PROVIDER = "github"


def default_config_path() -> Path:
    """Return the default config file path: ``~/.gtopt_check_json.conf``."""
    return Path.home() / ".gtopt_check_json.conf"


def read_git_email() -> str:
    """Read the user e-mail from the git global configuration.

    Returns an empty string when git is not installed or no email is set.
    """
    git_bin = shutil.which("git")
    if git_bin is None:
        return ""
    try:
        result = subprocess.run(
            [git_bin, "config", "--global", "user.email"],
            capture_output=True,
            text=True,
            timeout=5,
            check=False,
        )
        return result.stdout.strip()
    except (OSError, subprocess.TimeoutExpired):
        return ""


def load_config(config_path: Path) -> dict[str, str]:
    """Load the config file at *config_path*.

    Returns a dict with keys from :data:`_CONFIG_DEFAULTS`.  Missing keys are
    filled with the defaults.  Returns defaults when the file is absent.
    """
    cfg = dict(_CONFIG_DEFAULTS)
    if not config_path.exists():
        return cfg

    parser = configparser.ConfigParser()
    try:
        parser.read(config_path, encoding="utf-8")
    except configparser.Error:
        return cfg

    if parser.has_section(_CONFIG_SECTION):
        for key in _CONFIG_DEFAULTS:
            if parser.has_option(_CONFIG_SECTION, key):
                cfg[key] = parser.get(_CONFIG_SECTION, key)
    return cfg


def save_config(config_path: Path, cfg: dict[str, str]) -> None:
    """Write *cfg* to *config_path* in INI format."""
    parser = configparser.ConfigParser()
    parser[_CONFIG_SECTION] = cfg
    try:
        config_path.parent.mkdir(parents=True, exist_ok=True)
        with config_path.open("w", encoding="utf-8") as fh:
            fh.write(
                "# gtopt_check_json configuration\n"
                "# Generated by gtopt_check_json --init-config\n"
                "# Edit this file to set your defaults.\n"
                "#\n"
                "# Each check_* key can be set to 'true' or 'false'\n"
                "# to enable or disable individual checks.\n\n"
            )
            parser.write(fh)
    except OSError as exc:
        print(
            f"Warning: could not write config file {config_path}: {exc}",
            file=sys.stderr,
        )


def is_check_enabled(cfg: dict[str, str], check_id: str) -> bool:
    """Return True if *check_id* is enabled in *cfg*."""
    key = f"check_{check_id}"
    return cfg.get(key, CHECK_DEFAULTS.get(check_id, "true")).lower() in (
        "true",
        "1",
        "yes",
    )


def run_interactive_setup(config_path: Path, use_color: bool = True) -> dict[str, str]:
    """Run the interactive first-run setup wizard.

    Reads the git email as a proposed default, prompts for check
    enable/disable settings and AI configuration, then writes the
    resulting config to *config_path*.

    Returns the final config dict.
    """

    def _c(code: str, text: str) -> str:
        return f"{code}{text}{col.RESET}" if use_color else text

    print()
    print(_c(col.BOLD, "─── gtopt_check_json first-run setup ───"))
    print(
        "\nThis tool validates gtopt JSON planning files."
        "\nLet's configure which checks to enable."
    )

    cfg = load_config(config_path)

    # ── Color ──────────────────────────────────────────────────────────────
    current_color = cfg.get("color", "auto")
    color = _prompt("  Color output ('auto', 'always', 'never')", current_color)
    if color not in ("auto", "always", "never"):
        color = "auto"
    cfg["color"] = color

    # ── Checks ─────────────────────────────────────────────────────────────
    print()
    print(_c(col.BOLD, "Checks:"))
    for check_id, default_val in CHECK_DEFAULTS.items():
        current = cfg.get(f"check_{check_id}", default_val)
        answer = _prompt(f"  {check_id} (true/false)", current)
        if answer.lower() not in ("true", "false", "1", "0", "yes", "no"):
            answer = default_val
        cfg[f"check_{check_id}"] = answer

    # ── AI settings ────────────────────────────────────────────────────────
    print()
    print(_c(col.BOLD, "AI diagnostics:"))
    print(
        "\n  When an API key is available, gtopt_check_json can send system"
        "\n  information to an AI provider for an expert diagnosis."
        "\n  Supported providers: " + ", ".join(_AI_PROVIDERS)
    )

    current_ai = cfg.get("ai_enabled", "false")
    ai_str = _prompt("  Enable AI diagnostics ('true' or 'false')", current_ai)
    if ai_str.lower() not in ("true", "false", "1", "0", "yes", "no"):
        ai_str = "false"
    cfg["ai_enabled"] = ai_str

    current_ai_provider = cfg.get("ai_provider", _AI_DEFAULT_PROVIDER)
    provider_choices_str = _c(col.CYAN, str(list(_AI_PROVIDERS)))
    ai_provider = _prompt(
        f"  Preferred AI provider {provider_choices_str}", current_ai_provider
    )
    if ai_provider not in _AI_PROVIDERS:
        print(f"  Unknown provider '{ai_provider}', using '{_AI_DEFAULT_PROVIDER}'")
        ai_provider = _AI_DEFAULT_PROVIDER
    cfg["ai_provider"] = ai_provider

    current_ai_model = cfg.get("ai_model", "")
    ai_model = _prompt(
        "  AI model override (leave blank for provider default)",
        current_ai_model,
    )
    cfg["ai_model"] = ai_model

    # ── Save ───────────────────────────────────────────────────────────────
    save_config(config_path, cfg)
    print()
    print(f"  {_c(col.GREEN, '✓')} Configuration saved to: {config_path}")
    print()
    return cfg


def _prompt(prompt_text: str, default: str = "") -> str:
    """Prompt the user for input, showing a default if provided."""
    if not sys.stdin.isatty():
        return default
    full_prompt = f"{prompt_text} [{default}]: " if default else f"{prompt_text}: "
    try:
        answer = input(full_prompt).strip()
        return answer if answer else default
    except (EOFError, KeyboardInterrupt):
        return default
